<h1>Tabla de Contenidos<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#SITUACIÓN-PROFESIONAL-1" data-toc-modified-id="SITUACIÓN-PROFESIONAL-1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>SITUACIÓN PROFESIONAL 1</a></span><ul class="toc-item"><li><span><a href="#CLASE-4" data-toc-modified-id="CLASE-4-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>CLASE 4</a></span><ul class="toc-item"><li><span><a href="#Prof.-Ricardo-Piña" data-toc-modified-id="Prof.-Ricardo-Piña-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Prof. Ricardo Piña</a></span></li></ul></li></ul></li><li><span><a href="#NUMPY-EJERCICIOS" data-toc-modified-id="NUMPY-EJERCICIOS-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>NUMPY EJERCICIOS</a></span></li><li><span><a href="#Selección-de-elementos-de-un-array-según-su-valor" data-toc-modified-id="Selección-de-elementos-de-un-array-según-su-valor-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Selección de elementos de un array según su valor</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Selección-de-un-elemento-según-su-índice" data-toc-modified-id="Selección-de-un-elemento-según-su-índice-3.0.1"><span class="toc-item-num">3.0.1&nbsp;&nbsp;</span>Selección de un elemento según su índice</a></span></li></ul></li><li><span><a href="#FUNCIONES-LÓGICAS-de-Numpy" data-toc-modified-id="FUNCIONES-LÓGICAS-de-Numpy-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>FUNCIONES LÓGICAS de Numpy</a></span></li></ul></li><li><span><a href="#Funciones-de-agregados-de-datos-(por-fila,-por-columna,-etc)-de-NumPy" data-toc-modified-id="Funciones-de-agregados-de-datos-(por-fila,-por-columna,-etc)-de-NumPy-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Funciones de agregados de datos (por fila, por columna, etc) de NumPy</a></span><ul class="toc-item"><li><span><a href="#Reemplazar-valores-en-un-array" data-toc-modified-id="Reemplazar-valores-en-un-array-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Reemplazar valores en un array</a></span></li></ul></li><li><span><a href="#EXPRESIONES-VECTORIZADAS" data-toc-modified-id="EXPRESIONES-VECTORIZADAS-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>EXPRESIONES VECTORIZADAS</a></span><ul class="toc-item"><li><span><a href="#where" data-toc-modified-id="where-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>where</a></span></li></ul></li><li><span><a href="#CASO-1:-Sistemas-de-Recomendación-sin-personalización" data-toc-modified-id="CASO-1:-Sistemas-de-Recomendación-sin-personalización-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>CASO 1: Sistemas de Recomendación sin personalización</a></span></li><li><span><a href="#Guardar-arrays-de-NumPy" data-toc-modified-id="Guardar-arrays-de-NumPy-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Guardar arrays de NumPy</a></span></li></ul></div>

![IES21](img/logo_ies.png)

# COMPUTACIÓN CIENTÍFICA
## SITUACIÓN PROFESIONAL 1
### CLASE 4
#### Prof. Ricardo Piña

In [2]:
import numpy as np

## NUMPY EJERCICIOS

Creemos un vector (array de un solo eje) como el siguiente:  

vec_01=(0,10,20,...,100)


In [3]:
# Escriba aquí su código
vec_01=np.arange(0,110,10)
vec_01

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## Selección de elementos de un array según su valor

En la clase 2 habíamos visto cómo seleccionar elementos de un array, esencialmente según el valor del índice del elemento tanto para vectores como matrices o tensores.  
Simplemente para recordar cómo se hacía:

#### Selección de un elemento según su índice

Seleccionemos el elemento con índice 3 de vec_01

In [4]:
# Escriba aquí su código
vec_01[3]

30

Seleccionemos los elementos con índice 0, 3 y 7 de vec_01.  
Deberemos pasarle una secuencia con los índices deseados:

In [5]:
# Escriba aquí su código
vec_01[[0,3,7]]

array([ 0, 30, 70])

Seleccionemos los elementos de vec_01 con índice 1,3 y 4

In [6]:
# Escriba aquí su código
vec_01[[1,3,4]]

array([10, 30, 40])

Hemos visto que si pasamos los índices de los elementos que deseamos, numpy nos devuelve los valores almacenados en las ubicaciones corrrespondientes a dichos índices.  

Por otro lado, la clase pasada vimos que el resultado de una operación de comparación entre un array y un valor numérico por ejemplo nos daba un array con la secuencia True o False según correspondiera.  
**Podemos valernos de estos dos hechos para conseguir que nos devuelva los valores de un array que verifican ciertas condiciones:** 



**Ejercicio:** Supongamos que queremos obtener todos los valors de vec_01 cuyo valor es menor que 60.  

**Solución:**  

1. Primero podemos obtener el array con valores booleanos True o False con respecto a la condición "menor a 60"

In [7]:
vec_01<60

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

2. Luego pasamos este vector como los índices de los valores que queremos obtener 

In [8]:
vec_01[ vec_01<60]

array([ 0, 10, 20, 30, 40, 50])

**Ejercicio:** queremos obtener todos los valors de vec_01 cuyo valor es mayor o igual a 30.  

In [9]:
# Escriba aquí su código
vec_01[vec_01>=30]

array([ 30,  40,  50,  60,  70,  80,  90, 100])

### FUNCIONES LÓGICAS de Numpy

Las funciones lógicas implementadas en NumPy son:

- np.logical_and()   https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_and.html
- np.logical_or()    https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_or.html#numpy.logical_or
- logical_not()      https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_not.html#numpy.logical_not
- logical_xor()      https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_xor.html#numpy.logical_xor
- bitwise_and()      https://docs.scipy.org/doc/numpy/reference/generated/numpy.bitwise_and.html#numpy.bitwise_and
- bitwise_or()       https://docs.scipy.org/doc/numpy/reference/generated/numpy.bitwise_xor.html#numpy.bitwise_or


Ejercicio: En qué posiciones de vec_01 se encuentran los valores menores a 70?

**Ejercicio:** Cuál es el promedio de los valores de vec_01 menores a 70?  

In [12]:
# Escriba aquí su código
np.mean(vec_01[ vec_01<70])

30.0

**Ejercicio:** Cuáles son los elementos de vec_01 mayores que 35 **y** menores o iguales que 60?


Podemos resolverlo con np.logical_and ya que queremos que se cumplan ambas condiciones.  

Primero podemos encontrar un array de True y False en las ubicaciones donde las condiciones se cumplen o no usando 

np.logical_and(condicion1,condicion2)


In [13]:
# Escriba aquí su código
np.logical_and(vec_01>35,vec_01<=60) 

array([False, False, False, False,  True,  True,  True, False, False,
       False, False])

Si quisiéramos saber cuáles son estos valores:

In [14]:
# Escriba aquí su código
vec_01[np.logical_and(vec_01>35,vec_01<=60)]

array([40, 50, 60])

**Ejercicio:**

Cree la matriz mat_01 de 100 filas y 4 columnas, cuyos elementos son float (decimales) aleatorios de una distribución uniforme entre [0,100[ obtenidos con una semilla = (123)

In [15]:
# Escriba aquí su código
np.random.seed(123)
mat_01=np.array(np.random.uniform(0,100,400).reshape(100,4))
# también se podría usar:
# mat_01=np.random.uniform(0,100,(100,4)

# veamos la matriz mat_01
mat_01

array([[69.64691856, 28.6139335 , 22.68514536, 55.13147691],
       [71.94689698, 42.31064601, 98.07641984, 68.48297386],
       [48.09319015, 39.21175182, 34.31780162, 72.90497074],
       [43.85722447,  5.96778966, 39.80442553, 73.79954057],
       [18.24917305, 17.54517561, 53.15513738, 53.18275871],
       [63.44009586, 84.94317941, 72.44553249, 61.10235107],
       [72.24433826, 32.29589139, 36.17886556, 22.82632309],
       [29.37140464, 63.09761239,  9.21049399, 43.37011727],
       [43.08627633, 49.36850977, 42.58302903, 31.2261223 ],
       [42.6351307 , 89.33891631, 94.41600182, 50.18366759],
       [62.39529518, 11.56183951, 31.72854818, 41.4826212 ],
       [86.63091579, 25.04553654, 48.30342643, 98.55597856],
       [51.94851193, 61.28945258, 12.0628666 , 82.63408005],
       [60.30601284, 54.50680065, 34.27638338, 30.4120789 ],
       [41.7022211 , 68.13007658, 87.54568418, 51.04223375],
       [66.9313783 , 58.59365526, 62.49035021, 67.4689051 ],
       [84.23424376,  8.

Cuántos elmentos mayores a 50 hay en total?

Primero podríamos encontrar una matriz como mat_01 poblada por valores True o False según se cumpla la condición indicada:

In [16]:
# Escriba aquí su código
mat_01>50

array([[ True, False, False,  True],
       [ True, False,  True,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True, False, False, False],
       [ True, False, False,  True],
       [ True,  True, False,  True],
       [ True,  True, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True, False,  True],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [ True,  True, False, False],
       [False, False,  True,  True],
       [False,  True,  True,  True],
       [False, False, False, False],
       [ True,  True, False, False],
       [False,  True,  True,  True],
 

**Use np.sum()**  
np.sum(array, axis="eje por el que desea sumar")  

- Si omite axis entonces suma **todos** los elementos
- axis=0 suma por columnas
- axis= 1 suma por filas


In [17]:
# Escriba aqui su código
np.sum(mat_01>50)

199

Ejercicio:  

Cuántos elementos mayores que 50 hay en cada columna?

In [18]:
# Escriba aqui su código
np.sum(mat_01>50,axis=0)

array([50, 53, 43, 53])

Ejercicio:  

Y cuántos en cada fila?

In [19]:
# Escriba aqui su código
np.sum(mat_01>50,axis=1)

array([2, 3, 1, 1, 2, 4, 1, 1, 0, 3, 1, 2, 3, 2, 3, 4, 2, 2, 3, 2, 2, 2,
       2, 3, 0, 2, 3, 1, 2, 3, 2, 3, 2, 3, 1, 2, 2, 3, 1, 3, 2, 3, 3, 3,
       0, 2, 2, 3, 2, 1, 3, 3, 3, 1, 1, 2, 2, 0, 2, 3, 1, 1, 2, 2, 2, 2,
       0, 1, 1, 2, 2, 3, 3, 2, 3, 1, 2, 3, 1, 4, 1, 1, 3, 2, 1, 3, 0, 4,
       0, 1, 2, 2, 4, 2, 2, 3, 2, 1, 1, 1])

**Ejercicio:**  
Cuántos elementos mayores que 20 y menores o iguales que 50 tiene mat_01?

Podemos resolverlo por partes: 

- Primero podemos buscar qué elementos de mat_01 verifican o no las dos condiciones indicadas

In [20]:
# Escriba aqui su código
np.logical_and(mat_01>20,mat_01<=50)


array([[False,  True,  True, False],
       [False,  True, False, False],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False,  True,  True],
       [False,  True,  True, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False,  True],
       [False, False,  True, False],
       [ True,  True, False, False],
       [ True, False, False, False],
       [False,  True,  True,  True],
       [False, False, False, False],
       [ True, False, False, False],
 

2- Luego podemos "sumar los True"

In [21]:
# Escriba aqui su código
np.sum(np.logical_and(mat_01>20,mat_01<=50))

131

Cuántos elementos mayores a 20 y menores o iguales a 50 hay en cada columna?

In [22]:
# Escriba aqui su código
np.sum(np.logical_and(mat_01>20,mat_01<=50),axis=0)

array([33, 31, 37, 30])

y cuántos en cada fila?

In [23]:
# Escriba aqui su código
np.sum(np.logical_and(mat_01>20,mat_01<=50),axis=1)

array([2, 1, 3, 2, 0, 0, 3, 2, 4, 1, 2, 2, 0, 2, 1, 0, 1, 0, 0, 0, 2, 1,
       2, 1, 3, 0, 1, 3, 1, 0, 2, 1, 1, 0, 3, 1, 1, 0, 2, 1, 1, 1, 0, 0,
       2, 1, 1, 1, 1, 1, 0, 0, 0, 3, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1,
       3, 3, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 3, 0, 1, 2, 0, 2, 3, 1, 4, 0,
       3, 1, 1, 2, 0, 2, 2, 1, 2, 1, 3, 3])

## Funciones de agregados de datos (por fila, por columna, etc) de NumPy

Este tipo funciones que se aplican a las filas o columnas son muy utilizadas. 

Ya hemos utilizado una, **np.sum()**, otras que pueden ser de utilidad son:

- np.sum()
- np.min()
- np.argmin() ojo sólo devuelve la primer ocurrencia
- np.max()
- np.argmax()ojo sólo devuelve la primer ocurrencia
- np.mean()       
- np.median()

> Puede buscar su sintaxis en el manual de NumPy https://docs.scipy.org/doc/numpy/index.html reemplazando np por numpy  


**Nota** también puede usarse la sintaxis array.funcion(), por ejemplo para calcular el menor valor en el array A, podemos usar:  
- np.min(A)
- A.min()



**Ejercicios**

Cuál es el menor valor que tiene la matriz mat_01?

In [24]:
# Escriba aqui su código
np.min(mat_01)

0.2688064574320692

Cuál es el menor valor de cada una de las columnas de mat_01?

In [25]:
# Escriba aqui su código
np.min(mat_01,axis=0)

array([0.3532211 , 0.60278857, 0.26880646, 2.61966053])

El menor valor de cada fila de mat_01?

In [26]:
# Escriba aqui su código
np.min(mat_01,axis=1)

array([22.68514536, 42.31064601, 34.31780162,  5.96778966, 17.54517561,
       61.10235107, 22.82632309,  9.21049399, 31.2261223 , 42.6351307 ,
       11.56183951, 25.04553654, 12.0628666 , 30.4120789 , 41.7022211 ,
       58.59365526,  8.31949883,  9.57125166,  1.61292067, 15.30705151,
       31.87664264,  4.35914638, 30.47680734, 35.59148657, 15.11274523,
       10.59084851, 32.19806065, 31.67878971, 17.10818292,  0.26880646,
       20.76358612, 25.75420642, 16.10690144,  7.93657904, 20.45428595,
        9.33267104,  4.85790328, 16.59378842, 11.13921716, 44.03278767,
        8.49041632, 33.70663834,  7.91489607, 12.86311975,  8.17800871,
       12.22435496,  0.74263785, 20.60957274,  2.93197229,  3.21979349,
        6.67744432, 10.26352592,  4.90971306, 41.15692232, 18.16288427,
       23.65998117,  9.12963422,  4.73395372,  4.32228921, 30.19468363,
        0.55454084,  9.70381586, 20.82482967, 19.10069554,  2.52423578,
        6.74486351, 10.54458661, 28.12347815,  0.59428437,  2.61

Cuál es el promedio de cada columna de mat-01?

In [27]:
# Escriba aqui su código
np.mean(mat_01,axis=0)

array([48.75815882, 53.31766478, 46.74322832, 49.90467411])

y el promedio de cada fila?

In [28]:
# Escriba aqui su código
np.mean(mat_01,axis=1)

array([44.01936858, 70.20423417, 48.63192858, 40.85724506, 35.53306119,
       70.4827897 , 40.88635457, 36.26240707, 41.56598436, 69.1434291 ,
       36.79207602, 64.63396433, 51.98372779, 44.87531894, 62.1050539 ,
       63.87107222, 48.32216605, 43.69298152, 49.03066041, 39.10862201,
       48.85176364, 54.19478793, 60.0817767 , 60.08353487, 28.35789142,
       35.4139035 , 59.58271283, 47.75857179, 47.28088462, 52.27795028,
       48.13692507, 67.68608412, 52.33701971, 63.23626064, 40.78225493,
       47.16938644, 50.03447933, 62.37191414, 34.24150018, 67.23420966,
       46.3464161 , 66.55394384, 53.88934438, 67.98490115, 26.09703078,
       42.43764445, 45.8736222 , 60.94902242, 42.81474698, 34.29114869,
       56.47153919, 53.64101962, 50.53202227, 52.66625916, 38.38461219,
       63.99394282, 49.38907176, 17.45559415, 49.6060543 , 61.20858048,
       46.34922285, 46.59454999, 56.23462657, 57.11555807, 45.20895976,
       44.97538482, 23.15574372, 39.46409865, 26.68909471, 38.72

y el promedio de toda la matriz?

In [29]:
# Escriba aqui su código
np.mean(mat_01)

49.68093150915836

Cuántos elementos de mat_01 se encuentran por sobre el promedio?

In [30]:
# Escriba aqui su código
np.sum(mat_01>np.mean(mat_01))

199

y cuántos por debajo del promedio?

In [31]:
# Escriba aqui su código
np.sum(mat_01<np.mean(mat_01))

201

Se nota que los valores de mat_01 fueron obtenidos al azar y con una distribución uniforme, no es cierto?

Para cuántas filas de mat_01 el promedio de sus valores es mayor o igual que el promedio de toda la matriz?

In [32]:
# Escriba aqui su código
np.sum(np.mean(mat_01,axis=1)>=np.mean(mat_01))

47

Para cuántas columnas de mat_01 su promedio está por debajo del promedio de toda la matriz?

In [33]:
# Escriba aqui su código
np.sum(np.mean(mat_01,axis=0)<np.mean(mat_01))

2

### Reemplazar valores en un array

Creemos un vector como v1=(0,1,...10)

In [34]:
# Escriba aqui su código
v1=np.array(np.arange(0,11,1))
# muestre v1
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Reemplacemos el elemento de índice 3 elemento por el valor 7

El reemplazo lo hacemos simplemente asignando el valor deseado

In [35]:
v1[3]=7
v1

array([ 0,  1,  2,  7,  4,  5,  6,  7,  8,  9, 10])

Ahora reemplace los elementos que de índices 1,5 y 8 por el valor 7

In [36]:
# Escriba aqui su código
v1[[1,5,8]]=7
v1

array([ 0,  7,  2,  7,  4,  7,  6,  7,  7,  9, 10])

## EXPRESIONES VECTORIZADAS

### where

Una expresión que puede resultar de gran utilidad es  

where()  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html?highlight=numpy%20where#numpy.where

Esencialmente su funcionamiento es where(condición, si es vardadera la condición, si es falsa la condición).  

Se suele utilizar mucho para reemplazar valores en arrays:


Ahora, cree un vector v2 que se obtiene reemplazando todos los elementos de v1 con valor 7 por el valor 12 y el resto deben que quedar sin modificar. 

In [37]:
# Escriba aqui su código
v2=np.where(v1==7,12,v1)

# Muestre el vector v2 para estar seguros que lo hizo bien
v2

array([ 0, 12,  2, 12,  4, 12,  6, 12, 12,  9, 10])

Ejercicio:
Vamos a comenzar a pensar en nuestro Sistemas de Recomendaciones.  

Supongamos que poseemos en un archivo csv los ratings dados a ciertas perlículas por nuestros usuarios.  

- En este caso hemos organizado la información de tal manera que cada fila corresponde a un usuario y cada columna a una película.

- Los ratings asignados van de 1 a 5, cuando figura un 0 es porque esa película no ha sido calificada por ese usuario.

1- Lea el archivo data/ratings_01.csv cuyo separador es el ; asígnele el nombre ratings

In [38]:
ratings=np.genfromtxt("data/ratings_01.csv", delimiter=';')

In [39]:
ratings

array([[5., 0., 4., 2., 3.],
       [0., 1., 2., 2., 2.],
       [1., 4., 0., 0., 0.],
       [4., 3., 4., 2., 1.],
       [2., 0., 4., 5., 3.],
       [0., 0., 0., 5., 0.],
       [2., 4., 3., 0., 2.],
       [1., 0., 2., 0., 4.],
       [2., 5., 4., 3., 0.],
       [3., 0., 5., 4., 5.]])

Cuántos usuarios y cuántas películas tenemos en la matriz?

In [40]:
# Escriba aqui su código
ratings.shape

(10, 5)

Rta: 10 usuarios(filas) y 5 películas (columnas)

En total cuántas calificaciones válidas hay? (asuma que no hay valores "nan" Not a Number)

In [41]:
# Escriba aqui su código
np.sum(ratings!=0)

35

Cuántas calificaciones quedaron con valor 0, es decir sin calificar?

In [42]:
# Escriba aqui su código
np.sum(ratings==0)

15

## CASO 1: Sistemas de Recomendación sin personalización

Suponga que tiene que recomendar una película a un usuario totalmente nuevo, usted no tiene ningún dato sobre él, nunca ha calificado a ninguna película, nada; situación que se suele llamar "arranque en frío".  

Qué película le recomendaría?  
Aunque le parezca extremadamente simple, una respuesta podría ser: la que tenga mejor rating dado por el resto de lo usuarios.  
Y cuál sería la película con el "mejor rating"?  
Una respuesta podría ser la película que tuviera el mayor promedio de los ratings.  

Manos a la obra, calcule el promedio de rankings para cada película.

Seguramente estará tentado de calcular el promedio para cada columna, pero tenemos el problema de que hemos asignado el valor 0 a los casos donde no tenemos rating ...  
Lo ayudaré con éso.  
Crearemos una matriz ratingsNAN que será igual que la matriz ratings, pero en la cual habremos reemplazado los 0 por nan (not a number), y éstos no se toman en consideración al efectuar los cálculos como el promedio, la suma o la mediana si usamos las funciones correctas..  

1- Usará la función where  

2- Para asignar el valor nan debe escribirlo como np.nan



In [43]:
# Escriba aqui su código
ratingsNAN=np.where(ratings==0,np.nan,ratings)
ratingsNAN

# otra alternativa hubiera sido 
# ratingsNAN=ratings
# ratingsNAN[ratingsNAN==0]=np.nan
# ratingsNAN

array([[ 5., nan,  4.,  2.,  3.],
       [nan,  1.,  2.,  2.,  2.],
       [ 1.,  4., nan, nan, nan],
       [ 4.,  3.,  4.,  2.,  1.],
       [ 2., nan,  4.,  5.,  3.],
       [nan, nan, nan,  5., nan],
       [ 2.,  4.,  3., nan,  2.],
       [ 1., nan,  2., nan,  4.],
       [ 2.,  5.,  4.,  3., nan],
       [ 3., nan,  5.,  4.,  5.]])

Si usa la función np.mean va a dar error por los valores nan que tenemos ahora en la matriz.  
En este caso se debe usar:  

**np.nanmean()**  

También existe una función  
- **np.nanmedian()** para calcular la mediana
- **np.nansum()** para calcular la suma, etc

Calcule ahora el promedio de calificaciones válidas para cada película.

In [45]:
# Escriba aqui su código
promedios_pelis=np.nanmean(ratingsNAN,axis=0)
promedios_pelis

array([2.5       , 3.4       , 3.5       , 3.28571429, 2.85714286])

Calculemos el máximo valor entre estos promedios:

In [46]:
# Escriba aqui su código
np.max(promedios_pelis)

3.5

Para el usuario absolutamente nuevo con arranque en frío, le podríamos recomendar una película con un rating promedio de 3.5 que sería la película con mejor calificación.

Qué índice tiene esta película? (ayuda use argmax()), pero tenga cuidado porque **sólo** devuelve el índice de la **primer** ocurrencia del valor, si aparece más veces el valor máximo, no sabremos dónde está!

In [47]:
np.argmax(promedios_pelis)

2

Ahora calculemos el promedio de ratings de cada usuario:

In [293]:
# Escriba aqui su código
np.nanmean(ratingsNAN,axis=1)

array([3.5       , 1.75      , 2.5       , 2.8       , 3.5       ,
       5.        , 2.75      , 2.33333333, 3.5       , 4.25      ])

y también calcule el promedio de todos los ratings, guárdelo en la variable promedio

In [294]:
# Escriba aqui su código
promedio=np.nanmean(ratingsNAN)
promedio

3.085714285714286

## Guardar arrays de NumPy

Ahora tenemos dos arrays que seguramente desearemos utilizar en otro momento, así que sería útil guardarlos como tales.  

Para guardar nuestros arrays utilizaremos: 

- **np.save(path, array)**        https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html  

En el link encontrará todas las opciones.  
La extensión del archivo será **.npy**


In [300]:
np.save("data/ratings",ratings)

In [301]:
np.save("data/ratingsNAN",ratingsNAN)