In [1]:
import numpy as np

## EJERCICIOS PARA PRACTICAR 
correspondientes a las Clases 01 a 03.

### Cree una secuencia con todos los números enteros múltipos de 0 hasta el 100, llámela s1 

In [6]:
# Escriba su código aquí
s1=np.arange(0,101,10)
s1

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### Cuántos elementos tiene?

In [8]:
# Escriba su código aquí
np.size(s1)

11

### Utilice lo visto anteriormente para calcular cuántos numéros enteros múltiplos de 23 existen entre 0 y 15 millones.

In [11]:
# Escriba su código aquí
v1=np.arange(0,15000001,23)
np.size(v1)

652174

### Cree la matriz M, esta matriz tiene 6 filas y 6 columnas y está formada por los números aleatorios enteros comprendidos entre -100 y 100 que se obtienen utilizando una semilla de valor 123. Luego calcule el determinante de dicha matriz.

In [20]:
# Escriba su código aquí
np.random.seed(123)
M= np.random.randint(-100, 101, (6,6))
print(M)
Det=np.linalg.det(M)
Det

[[  9  26 -34  -2 -83 -17]
 [  6  23 -43  -4  13  26]
 [-53 -27 -68  74  11  53]
 [-17 -22  64  -4 -32 -51]
 [-45  95 -98 -16 -61 -34]
 [-16 -53  89  76  35   5]]


-11801315701.999994

### Cuánto vale el elemento ubicado en la 2da fila y 3er columna?

In [21]:
# Escriba su código aquí
M[1,2]

-43

### En qué posiciones de M los elementos son mayores que 0?

In [22]:
# Escriba su código aquí
M>0

array([[ True,  True, False, False, False, False],
       [ True,  True, False, False,  True,  True],
       [False, False, False,  True,  True,  True],
       [False, False,  True, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True,  True,  True,  True]])

### Ahora calcule 

sum(M>0)  

e interprete el resultado

In [23]:
# Escriba aquí su código
sum(M>0)


array([2, 3, 2, 2, 3, 3])

Interpretación: El resultado que devuelve es un vector que indica cuantos True hay por cada columna. Es decir cuantas posiciones cumplen con la condicion de ser mayor a 0

### En base a lo anterior, calcule cuántos elementos de M son mayores que 0

In [24]:
# Escriba su código aquí

sum(sum(M>0))

15

### Calcule la inversa de M, llámela Minv

In [26]:
# Escriba su código aquí
Minv=np.linalg.inv(M)
Minv

array([[ 0.00567232, -0.15209764, -0.01189955, -0.09807115,  0.0094948 ,
         0.0005678 ],
       [ 0.00356053,  0.09779139, -0.007536  ,  0.04118487,  0.00169787,
         0.01510337],
       [ 0.00535678,  0.15178941, -0.00119136,  0.0840726 , -0.01295434,
         0.01098753],
       [ 0.00356338, -0.1129714 , -0.00469882, -0.07225267,  0.01452029,
         0.01113511],
       [-0.01516459, -0.1008491 , -0.00493096, -0.05994558,  0.01248359,
        -0.00143263],
       [ 0.0125311 ,  0.27113388,  0.00918477,  0.14409918, -0.02912547,
         0.00710939]])

### Una propiedad de los determinantes dice que si multiplicamos el determinante de una matriz por el de su inversa, deberíamos obtener 1 por resultado. Verifíquelo.

In [35]:
# Escriba su código aquí

Detinv=np.linalg.det(Minv)
print (Detinv)
print (Det)
print (Det*Detinv)
if (Det*Detinv)== 1:
    print("Comprobado")
#No me da comprobado porque al final da 0033


    

-8.473631459842493e-11
-11801315701.999994
1.0000000000000033


### También sabemos que si multiplicamos una matriz por su inversa, deberíamos obtener la matriz identiad. Verifíquelo

In [37]:
# Escriba su código aquí
Mat_id=(M*Minv)
Mat_id

array([[ 5.10508990e-02, -3.95453866e+00,  4.04584751e-01,
         1.96142294e-01, -7.88068257e-01, -9.65266186e-03],
       [ 2.13631675e-02,  2.24920203e+00,  3.24047923e-01,
        -1.64739488e-01,  2.20723542e-02,  3.92687564e-01],
       [-2.83909268e-01, -4.09831395e+00,  8.10121834e-02,
         6.22137272e+00, -1.42497787e-01,  5.82339178e-01],
       [-6.05775171e-02,  2.48537079e+00, -3.00724625e-01,
         2.89010664e-01, -4.64649428e-01, -5.67890413e-01],
       [ 6.82406763e-01, -9.58066484e+00,  4.83233667e-01,
         9.59129236e-01, -7.61498986e-01,  4.87093597e-02],
       [-2.00497644e-01, -1.43700959e+01,  8.17444844e-01,
         1.09515376e+01, -1.01939138e+00,  3.55469560e-02]])

Seguramente observó que las posiciones que deberían valer 0 dan valores como -5.22444512e-7 la última parte del número, e-7 indica que es por diez a la menos 7 es decir que el número es: -0.0000005244512 ... prácticamente el 0 que esperábamos. Acostúmbrese que con métodos numéricos los resultados serán siempre aproximados. 