# Ejercicios de arrays com Numpy

## Ej1

Cree una matriz M que tenga 10 filas y 10 columnas. La primer fila deben ser los números del 1 al 10, la segunda los números del 11 al 20 y así sucesivamente hasta que la décima fila deben ser los números del 91 hasta el 100.  

Por supuesto que no la va a cargar "manualmente" elemento por elemento ... deberá pensar una forma que le abrevie el trabajo ...

In [1]:
# importe la librería Numpy
import numpy as np

In [4]:
# Escriba aquí su código
V_100=np.arange(1,101)
V_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
# Escriba aquí su código
M_100=np.reshape(V_100,[10,10])
M_100

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

## Ej2
Utilice un if para resolver el siguiente problema: Si el determinante de M es distinto de cero, entonces calcular la matriz inversa de M, si el determinante de M es cero imprima el mensaje "No se puede calcular la inversa".

In [7]:
# Escriba aquí su código
Det_M=np.linalg.det(M_100)
if Det_M!=0:
    inv_100=np.linalg.inv(M_100)
    print ("Inersa de la matriz:", inv_100)
else:
    print("No se puede calcular la inversa")

Inersa de la matriz: [[-5.63448427e+14  5.80276616e+14 -8.24866133e+13 -1.23590530e+11
   5.58755451e+13  1.65220408e+14  1.96005322e+13 -1.08291643e+12
   1.00756268e+13 -1.83907181e+14]
 [-7.32720305e+14  8.29599678e+14 -4.95547522e+13  2.50547885e+12
   8.13481004e+13  9.40985468e+13 -1.11082775e+14 -5.18499799e+13
  -5.66506864e+13 -5.69330476e+12]
 [ 1.86479826e+15 -1.92622785e+15  2.10056204e+14 -4.30953584e+12
  -3.31564914e+14 -4.11493336e+14  7.00299574e+13  1.20389241e+14
   3.50318128e+13  3.73290162e+14]
 [ 1.56605946e+15 -1.70008524e+15  1.03548453e+14 -2.86881536e+12
  -1.65010893e+14 -2.01359275e+14  8.18026217e+13  1.06255327e+14
  -2.89064712e+13  2.40564830e+14]
 [ 4.43198485e+15 -6.55389778e+15  3.33224829e+15 -8.85755511e+12
  -3.35498488e+14 -2.14318183e+15 -3.48645939e+14  3.39249867e+14
  -1.11616207e+14  1.39821480e+15]
 [-7.11406330e+15  9.35089372e+15 -3.59882829e+15  1.57253167e+13
   7.50124093e+14  2.66260632e+15  3.07413557e+14 -5.84430857e+14
   1.6244144

## Ej3
Cree una matriz de 5 filas y 5 columnas, sus elementos deben ser números enteros elegidos al azar entre 1 y 100 (utilice np.random.seed([123]) en la celda donde la calcule para que a todos nos dé el mismo resultado). Llame M1 a esta matriz:

In [20]:
np.random.seed([123]) 
M1=np.random.randint(1,100,(5,5))
M1

array([[52, 47,  8, 11, 22],
       [51, 16, 86, 86, 14],
       [10, 80, 76, 25, 45],
       [62, 74, 46, 50, 13],
       [29, 53, 85, 33, 59]])

## Ej4
Utilice un if para resolver el siguiente problema: Si el determinante de M1 es distinto de cero, entonces calcular la matriz inversa de M1 (llámela M1_inv), si el deterinante de M1 es cero imprima el mensaje "No se puede calcular la inversa".

In [21]:
# Escriba aquí su código
Det_M=np.linalg.det(M1)
if Det_M!=0:
    M1_inv=np.linalg.inv(M1)
    print ("Inersa de la matriz:", M1_inv)
else:
    print("No se puede calcular la inversa")

Inersa de la matriz: [[-0.12350131 -0.08131269 -0.13543418  0.14444672  0.13681589]
 [ 0.03019506  0.01388782  0.04158222 -0.02431963 -0.04091128]
 [-0.23691937 -0.13482613 -0.20104797  0.23862152  0.22109951]
 [ 0.26790316  0.17162105  0.24393015 -0.28141548 -0.26466135]
 [ 0.22506004  0.12574136  0.18242569 -0.23552767 -0.18405079]]


## Ej5

Si todo lo anterior salió bien Ud ha calculado la inversa de M1, M1_inv. Ahora queremos multiplicar matricialmente M por su inversa para ver si realmente da por resultado la matriz identidad (es posible que los valores que deberían ser cero no figuren como ceros sino como valores muy muy pequeños ... esto es así porque Numpy utiliza algoritmos especiales para acelererar el cálculo de la inversa!): 

In [24]:
# Escriba aquí su código
M_I=M1@M1_inv
M_I


array([[ 1.00000000e+00,  0.00000000e+00, -3.55271368e-15,
         2.66453526e-15,  8.88178420e-16],
       [ 3.10862447e-15,  1.00000000e+00,  0.00000000e+00,
         4.44089210e-16,  4.88498131e-15],
       [-1.77635684e-15, -8.88178420e-16,  1.00000000e+00,
        -1.77635684e-15,  0.00000000e+00],
       [ 0.00000000e+00, -2.22044605e-16, -4.44089210e-16,
         1.00000000e+00, -4.44089210e-16],
       [ 0.00000000e+00,  1.77635684e-15,  0.00000000e+00,
        -1.77635684e-15,  1.00000000e+00]])

## Ej6  

Ahora vamos a calcular M2 a partir de M1. Para obtener M2 deberemos cambiar algunos valores de M1 de la siguiente manera:  

- Todos los elementos de M1 cuyo valor sean menores o iguales a 30 deberán ser cambiados por 0, todos los valores de M1 que sean mayores que  30 y menores o iguales que 60 deberán ser cambiados por 1, todos los restantes deberán quedar sin modificar.   

Sugerencia: si está tentado por usar un par de for anidados "clásicos"... piense nuevamente ... hay algo (mucho) más fácil de usar en numpy ...

In [45]:
# Escriba aquí su código
M2=np.where((M1<=30,0,M1),(M1>30,1,M1),(M1<=60,1,M1))

M1,M2

SystemError: <built-in function where> returned a result with an error set

# Respuestas

In [36]:
M

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [24]:
M1

array([[52, 47,  8, 11, 22],
       [51, 16, 86, 86, 14],
       [10, 80, 76, 25, 45],
       [62, 74, 46, 50, 13],
       [29, 53, 85, 33, 59]])

In [29]:
M1_inv

array([[-0.12350131, -0.08131269, -0.13543418,  0.14444672,  0.13681589],
       [ 0.03019506,  0.01388782,  0.04158222, -0.02431963, -0.04091128],
       [-0.23691937, -0.13482613, -0.20104797,  0.23862152,  0.22109951],
       [ 0.26790316,  0.17162105,  0.24393015, -0.28141548, -0.26466135],
       [ 0.22506004,  0.12574136,  0.18242569, -0.23552767, -0.18405079]])

In [32]:
M1@M1_inv

array([[ 1.00000000e+00,  4.44089210e-16,  1.16573418e-15,
        -2.77555756e-16,  1.55431223e-15],
       [ 2.94209102e-15,  1.00000000e+00,  5.55111512e-17,
        -5.38458167e-15, -1.11022302e-15],
       [-2.69229083e-15, -4.44089210e-16,  1.00000000e+00,
         2.58126853e-15,  2.33146835e-15],
       [ 4.16333634e-16,  4.44089210e-16,  2.30371278e-15,
         1.00000000e+00, -1.22124533e-15],
       [ 6.93889390e-16, -1.33226763e-15, -7.49400542e-16,
        -1.47104551e-15,  1.00000000e+00]])

In [35]:
M2

array([[ 1,  1,  0,  0,  0],
       [ 1,  0, 86, 86,  0],
       [ 0, 80, 76,  0,  1],
       [62, 74,  1,  1,  0],
       [ 0,  1, 85,  1,  1]])