# SP01 Ejercicios Vectores 1

In [3]:
# Importar las librería Numpy
import numpy as np

## Ej 1
Cree el siguiente array de Numpy y llámelo v1

$$ v1=[1,2,3,4,5,6,7,8,9,10, ..., 50] $$

In [4]:
# Escriba aquí su código
v1=np.arange(1,51,1)
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

## Ej 2
Cree el siguiente array de Numpy y llámelo v2

$$ v2=[2,4,6,8,10,...,100] $$

In [5]:
# Escriba aquí su código
v2=np.arange(2,101,2)
v2

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

## Ej 3
Cree el siguiente array de Numpy y llámelo v3

$$ v3=[3,6,9,12,...,150] $$

In [6]:
# Escriba aquí su código
v3=np.arange(3,151,3)
v3

array([  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
        42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,
        81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117,
       120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150])

## Ej 4

Calcule el módulo o norma de los vectores anteriores, llame a esto valores mod_v1 mod_v2 y mod_v3

In [7]:
# Escriba aquí su código
mod_v1=np.linalg.norm(v1)
mod_v1

207.18349355100662

In [8]:
# Escriba aquí su código
mod_v2=np.linalg.norm(v2)
mod_v2

414.36698710201324

In [9]:
# Escriba aquí su código
mod_v3=np.linalg.norm(v3)
mod_v3

621.5504806530198

## Ej 5

In [10]:
v1.size

50

Cree un vector que tenga la misma cantidad de elementos que los anteriores y que esté formado todo por números veinte, llámelo v_veintes.    

- Cuál de los vectores anteriores es más cercano a v_veintes?   
- Guarde el valor de la menor distancia en una variable llamada: min_dist 
- Cuál es el vector más lejaano a v_veintes? 
- Guarde este valor en nmax_dist

In [11]:
# Escriba aquí su código
v_veintes= np.full(50,20)
v_veintes


array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [12]:
# Escriba aquí su código
np.linalg.norm(v_veintes-v1)

109.20164833920778

In [13]:
# Escriba aquí su código

np.linalg.norm(v_veintes-v2)

299.4995826374387

In [14]:
# Escriba aquí su código

np.linalg.norm(v_veintes-v3)

503.3140172894055

In [15]:
# Escriba aquí su código
min_dist=np.linalg.norm(v_veintes-v1)
min_dist

109.20164833920778

In [16]:
# Escriba aquí su código
nmax_dist=np.linalg.norm(v_veintes-v3)
nmax_dist

503.3140172894055

## Ej 6

En álgebra se demuestra que el coseno del ángulo formado entre dos vectores puede calcularse a partir de la fórmula del producto interno de dos vectores:  

$$ u * v = |u| |v| cos(\alpha)$$  

de donde podemos despejar que:  

$$ cos(\alpha) = \frac {u * v}{|u| |v|}$$

Siendo $ \alpha$ el ángulo entre los vectores.  

En base a lo anterior calcule el ángulo (en grados) formado entre:  

- v1 y v2, llámelo alfa_12


Nota: dado que la fórmula anterior le permite calcular el coseno del ángulo, deberá buscar cómo se calcula el arco coseno de un ángulo en Python!


In [17]:
# Escriba aquí su código
import math
cos_alfa_12=(v1@v2/(mod_v1 * mod_v2))
alfa_12=np.rad2deg(math.acos(cos_alfa_12))
alfa_12

0.0

In [18]:
#Son paralelos

85850.0

## Respuestas

In [ ]:
v1

In [ ]:
v2

In [ ]:
v3

In [ ]:
mod_v1

In [ ]:
mod_v2

In [ ]:
mod_v3

In [ ]:
v_veintes

In [ ]:
min_dist

In [ ]:
max_dist

In [ ]:
alfa_12