![IES21](img/logo_ies.png)

# COMPUTACIÓN CIENTÍFICA
## Práctica para el Parcial 1

#### Prof. Ricardo Piña

En la carpeta data encontrará el archivo de Numpy *ratings_movie_lens.npy* con los datos correspondientes a clasificaciones de peliculas reales. 

In [1]:
import numpy as np

Cargue el array de datos ratings_movie_lens.npy en un array denominado calificaciones

Numpy cuenta con 

np.load('path') 

para leer archivos con extensión .npy. 

El path puede ser absoluto o relativo a la ubicación del archivo desde el cual se ejecuta np.load(), generalmente ésta es la opción que se utiliza.

En nuestro caso la disposición de los archivos es la siguiente:  


su_carpeta ______
                 |
                 |__Preparcial_1ALUMNO
                 |
                 |__data___
                           |
                           |_ratings_movie_lens.npy
                           
                           
Por lo cual el camino o path para acceder desde  este archivo, Preparcial_1ALUMNO hasta   ratings_movie_lens.npy es:

'data/ratings_movie_lens.npy'
                 

In [3]:
# Escriba aquí su código

calificaciones=np.load('data/ratings_movie_lens.npy')
calificaciones

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

Muestre algunos elementos de calificaciones

In [3]:
# Escriba aquí su código


Cada fila de *calificaciones* corresponde a un usuario y cada columna a una película reales.
Cuántos usuarios hay y cuántas películas hay?
- guarde el valor la cantidad de usuarios en la variable q_usuarios
- guarde la cantidad de películas en la variable q_peliculas

In [6]:
# Escriba aquí su código
q_usuarios= calificaciones.shape[0]

q_peliculas= calificaciones.shape[1]
# Muestre la cantidad de usuarios y de películas
q_usuarios, q_peliculas


(943, 1682)

Los valores van de 0 a 5:  
- el 0 indica que no se ha calificado a la película, 
- luego las calificaciones son de 1 a 5 siendo el 5 la mejor calificación.

Cuántas calificaciones "reales" (distintas de cero) ha hecho cada usuario?
Guarde el resultado en la variable q_calificaciones_reales

In [10]:
# Escriba aquí su código

q_calificaciones_reales=np.sum(calificaciones>0)
q_calificaciones_reales #todas


100000

In [17]:
calificacion_real=calificaciones>0
calificacion_real

array([[ True,  True,  True, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [ True, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False]])

In [18]:
#Escriba aqui su código
q_calificaciones_usuario= np.sum(calificacion_real, axis=1)
q_calificaciones_usuario

array([272,  62,  54,  24, 175, 211, 403,  59,  22, 184, 181,  51, 636,
        98, 104, 140,  28, 277,  20,  48, 179, 128, 151,  68,  78, 107,
        25,  79,  34,  43,  36,  41,  24,  20,  25,  20,  57, 121,  22,
        35,  52, 183, 221, 151,  48,  27,  25,  66, 215,  24,  23,  56,
        28,  65,  21, 187, 106, 154, 382, 208,  21, 232,  93, 200,  80,
        38,  30,  34,  65, 131,  38, 137,  66,  39,  79,  82,  72,  21,
        55,  29,  58, 168, 155,  68, 288,  23, 211,  21,  76, 300,  98,
       388,  20, 400, 278,  56,  63,  27, 136,  59,  67, 216,  29, 111,
        23,  64,  22,  33, 234, 133,  24,  46,  51,  48,  92, 143,  86,
        71, 181,  26,  74,  61,  54,  24, 182,  45,  23, 184,  30, 353,
        30,  22,  26,  25,  55,  35,  47,  51,  24,  21, 107,  33,  20,
       206, 316,  29,  20,  65,  36,  32, 307, 106,  23,  51,  22,  37,
        51, 173, 107, 120,  58,  42,  23,  63,  30,  20,  69,  69,  37,
        22,  28,  27,  43, 177,  38,  63, 115, 273,  42,  63, 43

In [22]:
#Escriba aqui su codigo
q_calificaciones_peliculas= np.sum(calificacion_real, axis=0)
q_calificaciones_peliculas

array([452, 131,  90, ...,   1,   1,   1])

In [8]:
# q_calificaciones_reales

Muestre la cantidad de calificaciones reales de los primeros 10 usuarios.
Guarde este resultado en la variable q_users_10

In [26]:
# Escriba aquí su código
q_users_10= q_calificaciones_usuario[0:10]
q_users_10

array([272,  62,  54,  24, 175, 211, 403,  59,  22, 184])

En promedio cuántas películas ha calificado cada usuario?
guarde el resultado en la variable q_promedio_pelis_xusuario

In [33]:
# Escriba aquí su código
q_promedio_pelis_xusuario=np.mean(q_calificaciones_usuario)
q_promedio_pelis_xusuario

106.04453870625663

Qué cantidad de calificaciones reales tiene cada una de las películas?

In [30]:
# Escriba aquí su código
q_calificaciones_peliculas= np.sum(calificacion_real, axis=0)
q_calificaciones_peliculas

array([452, 131,  90, ...,   1,   1,   1])

Muestre la cantidad de calificaciones reales de las primeras 10 películas.
Guarde este resultado en la variable q_calif_10_pelis

In [32]:
# Escriba aquí su código
q_calif_10_pelis=q_calificaciones_peliculas[0:10]
q_calif_10_pelis

array([452, 131,  90, 209,  86,  26, 392, 219, 299,  89])

## Problema 1: Sistemas de Recomendación  con Promedio

En este caso sencillamente deberá calcular la calificación promedio para cada una de las películas utilizando para ello las calificaciones válidas.  
- Deberá indicar cuál es el valor del **mejor promedio** entre todas las películas, guardándolo en la variable best_mean_rating
- y en qué número de columna se encuentra, guardando este valor en la varibale id_best_mean_rating

In [34]:
# Escriba aquí su código
sin_ceros=np.where(calificaciones==0,np.nan,calificaciones)
sin_ceros

array([[ 5.,  3.,  4., ..., nan, nan, nan],
       [ 4., nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [ 5., nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan,  5., nan, ..., nan, nan, nan]])

In [37]:
# Escriba aquí su código
promedios_pelis=np.nanmean(sin_ceros,axis=0)
promedios_pelis

array([3.87831858, 3.20610687, 3.03333333, ..., 2.        , 3.        ,
       3.        ])

In [38]:
# Escriba aquí su código para obtener best_mean rating

best_mean_rating=np.max(promedios_pelis)
best_mean_rating

5.0

In [39]:
# Escriba aquí su código

id_best_mean_rating=np.argmax(promedios_pelis)
id_best_mean_rating

813

Cuántas películas obtuvieron calificación promedio mayor o igual a 3?

In [42]:
# Escriba aquí su código
np.sum(promedios_pelis>=3)


1054

## REPORTE FINAL

Quite todos los comentarios a las celdas siguientes

In [27]:
# q_usuarios

In [28]:
# q_peliculas

In [29]:
# q_calificaciones_reales

In [30]:
# q_users_10

In [31]:
# q_promedio_pelis_xusuario

In [32]:
# q_calif_10_pelis

### PROBLEMA 1

In [33]:
# best_mean_rating

In [34]:
# id_best_mean_rating