<h1>Tabla de Contenidos<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#SITUACIÓN-PROFESIONAL-1" data-toc-modified-id="SITUACIÓN-PROFESIONAL-1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>SITUACIÓN PROFESIONAL 1</a></span><ul class="toc-item"><li><span><a href="#CLASE-2" data-toc-modified-id="CLASE-2-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>CLASE 2</a></span><ul class="toc-item"><li><span><a href="#Prof.-Ricardo-Piña" data-toc-modified-id="Prof.-Ricardo-Piña-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Prof. Ricardo Piña</a></span></li></ul></li></ul></li><li><span><a href="#Operaciones-elemento-a-elemento-o-element---wise-operations" data-toc-modified-id="Operaciones-elemento-a-elemento-o-element---wise-operations-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Operaciones elemento a elemento o element - wise operations</a></span><ul class="toc-item"><li><span><a href="#Cuidado:-element---wise-product" data-toc-modified-id="Cuidado:-element---wise-product-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Cuidado: element - wise product</a></span></li><li><span><a href="#Nota:" data-toc-modified-id="Nota:-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Nota:</a></span></li></ul></li><li><span><a href="#Operaciones-con-Matrices" data-toc-modified-id="Operaciones-con-Matrices-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Operaciones con Matrices</a></span><ul class="toc-item"><li><span><a href="#Producto-de-un-escalar-por-una-matriz" data-toc-modified-id="Producto-de-un-escalar-por-una-matriz-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Producto de un escalar por una matriz</a></span></li><li><span><a href="#Suma-de-matrices" data-toc-modified-id="Suma-de-matrices-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Suma de matrices</a></span></li><li><span><a href="#Producto-de-2-Matrices" data-toc-modified-id="Producto-de-2-Matrices-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Producto de 2 Matrices</a></span></li><li><span><a href="#Producto-elemento-a-elemento-&quot;element-wise&quot;de-matrices" data-toc-modified-id="Producto-elemento-a-elemento-&quot;element-wise&quot;de-matrices-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Producto elemento a elemento "element wise"de matrices</a></span></li><li><span><a href="#Inversa-de-una-Matriz" data-toc-modified-id="Inversa-de-una-Matriz-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Inversa de una Matriz</a></span></li><li><span><a href="#Determinante-de-una-matriz" data-toc-modified-id="Determinante-de-una-matriz-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Determinante de una matriz</a></span></li></ul></li><li><span><a href="#Selección-de-elementos-de-un-array-(vector,-matriz,-tensor)" data-toc-modified-id="Selección-de-elementos-de-un-array-(vector,-matriz,-tensor)-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Selección de elementos de un array (vector, matriz, tensor)</a></span><ul class="toc-item"><li><span><a href="#IMPORTANTE:" data-toc-modified-id="IMPORTANTE:-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>IMPORTANTE:</a></span></li><li><span><a href="#Uso-de-[-----]-con-vectores-o-arrays-de-un-solo-eje-(unidimensionales)" data-toc-modified-id="Uso-de-[-----]-con-vectores-o-arrays-de-un-solo-eje-(unidimensionales)-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Uso de <strong>[     ]</strong> con vectores o arrays de un solo eje (unidimensionales)</a></span></li><li><span><a href="#Uso-de-:-con-vectores-o-arrays-de-un-solo-eje--(unidimensionales)" data-toc-modified-id="Uso-de-:-con-vectores-o-arrays-de-un-solo-eje--(unidimensionales)-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Uso de : con vectores o arrays de un solo eje  (unidimensionales)</a></span></li><li><span><a href="#Uso-de-[-----]-con-matrices-o-arrays-de-2-ejes-(bidimensionales)" data-toc-modified-id="Uso-de-[-----]-con-matrices-o-arrays-de-2-ejes-(bidimensionales)-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Uso de <strong>[     ]</strong> con matrices o arrays de 2 ejes (bidimensionales)</a></span></li></ul></li></ul></div>

![IES21](img/logo_ies.png)

# COMPUTACIÓN CIENTÍFICA
## SITUACIÓN PROFESIONAL 1
### CLASE 2
#### Prof. Ricardo Piña

# Algebra en Python: Numpy

## Operaciones elemento a elemento o element - wise operations 

In [2]:
import numpy as np
u=np.array([1,2,3])
v=np.array([2,0,-4])
M=np.array([[3,1,-1,4],[2,5,1,2],[0,2,4,1]])

Los arrays de NumPy también incluyen otras operaciones que no están definidas en álgebra, pero que pueden resultarnos de utilidad al programar. 

Por ejemplo, para calcular la potencia de un número en Python, por ejemplo  $ 5^2 $ se utiliza doble asterisco **  

In [3]:
5**2

25

In [4]:
5**3

125

También se puede utilizar la función pow(base, potencia)

In [125]:
pow(2,3)

8

NumPy permite aplicar esta operación de potenciación a __todos los elementos de un vector (o de un array en general)__  
$$ u^2 $$ es decir $$(1,2,3)^2 $$ y efectuará la operación: 
$$ (1^2,2^2,3^2) $$

In [7]:
print("u= ", u)
u**2

u=  [1 2 3]


array([1, 4, 9], dtype=int32)

El mismo concepto se aplica a operaciones como:  

- raíz cuadrada: np.sqrt()
- funciones trigonométricas como sin(), cos(), tan()
- exponenciales

In [66]:
print(u)
np.sqrt(u)

[1 2 3]


array([1.        , 1.41421356, 1.73205081])

In [67]:
print(u)
np.sin(u)      # por defecto toma los ángulos en radianes

[1 2 3]


array([0.84147098, 0.90929743, 0.14112001])

In [68]:
print(u)
np.cos(u)      # por defecto toma los ángulos en radianes

[1 2 3]


array([ 0.54030231, -0.41614684, -0.9899925 ])

In [69]:
print(u)
np.tan(u)      # por defecto toma los ángulos en radianes

[1 2 3]


array([ 1.55740772, -2.18503986, -0.14254654])

Ahora veremos la función exponencial de un vector:

$ e^u$  donde e=2,718182...

In [70]:
print(u)
np.exp(u)      

[1 2 3]


array([ 2.71828183,  7.3890561 , 20.08553692])

In [71]:
print(u)
2**u      

[1 2 3]


array([2, 4, 8], dtype=int32)

### Cuidado: element - wise product 

Por ejemplo en álgebra no está definida la operación de "producto de dos vectores", pero en NumPy sí podemos multiplicarlos:

Recordemos quiénes son u y v y veamos qué hace NumPy cuando los multiplicamos:

In [72]:
print(u)
print(v)

print(u*v)

[1 2 3]
[ 2  0 -4]
[  2   0 -12]


Observamos que el resultado es otro vector, cuyas componentes surgen de multiplicar componente a componente ambos vectores. 

### Nota:
Si hubiera tenido que crear la función que calculara cualquiera de las operaciones anteriores sin NumPy, seguramente hubiera tenido que realizar un loop sobre los elementos del array. Computacionalmente los loops son costosos y si existe una función definida en NumPy que realiza la operación es **preferente** utilizarla, ya que en general están optimizadas. Además de ganar legibilidad en el código, mejoraremos los tiempos de ejecución!

## Operaciones con Matrices

### Producto de un escalar por una matriz

Se procede de la misma manera que en el producto de una escalar por un vector.  
Obtenga 5 M

In [3]:
# Escriba aquí su código
import numpy as np
M=np.array([[3,1,-1,4],[2,5,1,2],[0,2,4,1]])
5*M

array([[15,  5, -5, 20],
       [10, 25,  5, 10],
       [ 0, 10, 20,  5]])

### Suma de matrices

Se procede de la misma manera que para la suma de vectores

Cree la matriz $$N=\begin{bmatrix} 1 & -2 & 3 & 0\\ 0 & 2 & 1 & -2\\ 1 & 2 & 0 & 1 \end{bmatrix}$$  

y obtenga luego, M+N

In [4]:
# Escriba aquí su código
N=np.array([[1,-2,3,0],[0,2,1,-2],[1,2,0,1]])
M+N

array([[ 4, -1,  2,  4],
       [ 2,  7,  2,  0],
       [ 1,  4,  4,  2]])

### Producto de 2 Matrices

> CUIDADO:para calcular el producto **algebraico** de 2 matrices debe efectuar el **producto punto o producto interno entre ellas** de la misma manera que se hace el producto punto o interno entre vectores (puede usar np.dot() o @ ) no use el *!.



Cree la matriz $$P=\begin{bmatrix} 2 & 1 & 0 \\ 1 & 1 & 3 \end{bmatrix}$$  

In [5]:
# Escriba aquí su código
P=np.array([[2,1,0],[1,1,3]])
P

array([[2, 1, 0],
       [1, 1, 3]])

Imprima N para que la tengamos presente:

In [7]:
N

array([[ 1, -2,  3,  0],
       [ 0,  2,  1, -2],
       [ 1,  2,  0,  1]])

Ahora efectúe el producto P . N

In [8]:
# Escriba aquí su código
np.dot(P,N)

array([[ 2, -2,  7, -2],
       [ 4,  6,  4,  1]])

In [9]:
# Escriba aquí su código
P@N

array([[ 2, -2,  7, -2],
       [ 4,  6,  4,  1]])

También podría hacerse con el símbolo @

In [78]:
# Escriba aquí su código


Verifique que hizo la operación correcta.
Qué pasaría si efectuara el producto NP?

In [79]:
# Escriba aquí su código
# np.dot(N,P)
# después comente su línea de código
import numpy as np
N=np.array([[1,-2,3,0],[0,2,1,-2],[1,2,0,1]])
P=np.array([[2,1,0],[1,1,3]])
N@P #AL intentar hacer la operacion punto de N y P no se puede ya que algebraicamente es inaplicable,
#esto es porque la cantidad de columnas de N no coincide con la catidad de filas de P

### Producto elemento a elemento "element wise"de matrices

Si efectuamos el producto con el *, el producto será elemento a elemento. 

Calcule M*N y verifíque lo dicho.

In [10]:
# Escriba aquí su código
#M*N
M*N

array([[ 3, -2, -3,  0],
       [ 0, 10,  1, -4],
       [ 0,  4,  0,  1]])

In [11]:
# Escriba aquí su código
#N*M
N*M

array([[ 3, -2, -3,  0],
       [ 0, 10,  1, -4],
       [ 0,  4,  0,  1]])

Las operaciones de potencia ** y de exponencial y trigonométricas funcionan de la misma manera que con los vectores, es decir se efectúan elemento a elemento:

Calcule $$ P^2$$

In [12]:
print(P)

[[2 1 0]
 [1 1 3]]


In [13]:
# Escriba aquí su código
P**2

array([[4, 1, 0],
       [1, 1, 9]], dtype=int32)

Calcule $$ 2^P$$

In [14]:
# Escriba aquí su código
2**P


array([[4, 2, 1],
       [2, 2, 8]], dtype=int32)

Calcule $$ e^P$$

In [15]:
# Escriba aquí su código
np.exp(P)

array([[ 7.3890561 ,  2.71828183,  1.        ],
       [ 2.71828183,  2.71828183, 20.08553692]])

### Inversa de una Matriz

Para obtener la inversa de una matriz, debemos recurrir al paquete de Álgebra Lineal  

**linalg** ,  

la sintaxis sería:  

**np.linalg.inv(Matriz_Cuadrada)**

Cree la matriz cuadrada Q:

$$Q=\begin{bmatrix} 2 & 1  \\ 1 & 2  \end{bmatrix}$$  

In [16]:
# Escriba aquí su código
Q=np.array([[2,1],[1,2]])
Q

array([[2, 1],
       [1, 2]])

Ahora calcula la matriz inversa de Q, es decir $$ Q^-1 $$

In [17]:
# Escriba aquí su código
np.linalg.inv(Q)

array([[ 0.66666667, -0.33333333],
       [-0.33333333,  0.66666667]])

### Determinante de una matriz

Para obtener el determinante  de una matriz, debemos recurrir al paquete de Álgebra Lineal  

**linalg** ,  

la sintaxis sería:  

**np.linalg.det(Matriz_Cuadrada)**

Cree la matriz cuadrada R:

$$R=\begin{bmatrix} 3 & 2  \\ 1 & 5  \end{bmatrix}$$  

In [22]:
# Escriba aquí su código
R=np.array([[3,2],[1,5]])
R

array([[3, 2],
       [1, 5]])

Calcule el determinante de R

In [23]:
# Escriba aquí su código

np.linalg.det(R)


13.0

Calcule el determinante de Q

In [21]:
np.linalg.det(Q)

2.9999999999999996

## Selección de elementos de un array (vector, matriz, tensor)

### IMPORTANTE: 
lo primero que debemos saber al respecto es que en Python **los elementos de una secuencia se comienzan a enumerar o _indexar_ desde 0, no desde 1**.  

Esto significa que **el primer elemento de una secuencia ocupa la posición 0**

Así por ejemplo si tenemos el vector $$ w=(a,b,c) $$  
su **primer elemento es $a$** y ocupa la **posicion 0** dentro del vector $w$

Lo mismo ocurre para las matrices u otros arreglos. 

Por ejemplo en la matriz 
$$M=\begin{bmatrix} 3 & 1 & -1 & 4\\ 2 & 5 & 1 & 2\\ 0 & 2 & 4 & 1 \end{bmatrix}$$

Las filas (y también las columnas) se enumeran desde 0.   
Es decir que la primer fila es la fila 0:  
$$fila \, 0=\begin{bmatrix} 3 & 1 & -1 & 4 \end{bmatrix}$$  
Y la columna 0 es: 
$$columna\, 0=\begin{bmatrix} 3 \\ 2 \\ 0  \end{bmatrix}$$  

El 3 es "primer elemento de la matriz" y ocupa la posición (0,0): fila 0 y columna 0.


### Uso de **[     ]** con vectores o arrays de un solo eje (unidimensionales)

Para acceder a una posición dentro de un array se utilizan los corchetes 

**[ posición del elemento en cada eje separado por comas ]**  

Así por ejemplo si deseamos acceder al primer elemento de un vector como u=(1,2,3), como u tiene sólo un eje bastará escribir:  
u[0]

In [129]:
u[0]

1

Obtenga el tercer elemento del vector u

In [25]:
# Escibra aquí su código
u=np.array([1,2,3])
u[2]

3

Vamos a cargar un vector un poco más largo para que se pongan de manifiesto algunas características:  

$$ w=(10,20,30,40,50,60,70,80,90,100)$$


In [27]:
# Escriba aquí su código para crear el vector w 

w=np.array([10,20,30,40,50,60,70,80,90,100])
# muéstrelo


In [28]:
# Obtenga el primer elemento
w[0]

10

In [30]:
# Obtenga el cuarto elemento
w[3]

40

In [31]:
# Obtenga el décimo elemento
w[9]

100

### Uso de : con vectores o arrays de un solo eje  (unidimensionales)

Como ya estará pensando, debería haber alguna forma de poder obtener varios elementos juntos, por ejemplo los primeros 5 elementos o cosas por el estilo.   
Para ésto se utilizan los dos puntos **:**

Observe cómo funcionan los **:** con nuestro conocido vector  

$$ w=(10,20,30,40,50,60,70,80,90,100)$$

In [32]:
w[2:5]

array([30, 40, 50])

Como puede observar w[2:5] , devolvió los elementos con índices 2,3,y 4.  
Observe que **no** incluyó al elemento con índice 5. 

Podríamos pensarlo así:  

w[ desde este índice : hasta este índice pero **SIN** incluírlo ]


Le recuerdo quién era w  

$$ w=(10,20,30,40,50,60,70,80,90,100)$$

Escriba el código que devuelva [ 60,70,80,90 ]

In [33]:
# Escriba aquí su código:
w[5:9]


array([60, 70, 80, 90])

Otro, por las dudas ...
Escriba el código que devuelva [20,30,40,50,60]

In [34]:
# Escriba aquí su código:
w[1:6]

array([20, 30, 40, 50, 60])

Si se omite el valor "desde" asume que es desde el índice 0, es decir desde el primer elemento.


In [98]:
w[:4]

array([10, 20, 30, 40])

debería ser exactamente lo mismo que

In [99]:
w[0:4]

array([10, 20, 30, 40])

Obtenga los primeros seis elementos de w

In [35]:
# Escriba aquí su código

w[:6]

array([10, 20, 30, 40, 50, 60])

Si se omite el valor "hasta", asume que es hasta el último elemento.
Qué obtendríamos con  w[5: ]?

In [101]:
w[5:]

array([ 60,  70,  80,  90, 100])

Escriba el código para obtener los números desde el 40 hasta el 100, le recuerdo cómo era  

$$ w=(10,20,30,40,50,60,70,80,90,100)$$



In [36]:
# Escriba aquí su código
w[3:]

array([ 40,  50,  60,  70,  80,  90, 100])

Además puede indexarse contando desde el final ... usando índices negativos

In [103]:
w[-1]

100

In [104]:
w[-2]

90

In [133]:
w[-3:-1]

array([80, 90])

Cómo haría para obtener los 3 últimos elementos?

In [38]:
# Escriba aquí su código
w[-3:]

array([ 80,  90, 100])

Cómo haría para obtener los primeros 3 elementos?

In [39]:
# Escriba aquí su código
w[:3]

array([10, 20, 30])

Qué le parece que sería el resultado de w[ : ]?

In [41]:
# Escriba aquí su código
#La lista completa
w[:]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Tenga presente este resultado cuando investiguemos las matrices a continuación.

Hasta ahora hemos obtenido elementos que son contiguos. Cómo podríamos hacer si quisiéramos elementos que no son contiguos?  
Supongamos que queremos el primer, tercer y quinto elementos de w.  

1. Primero deberíamos crear un array con los índices que deseáramos obtener
2. Luego pasaríamos estos índices como parámetro

In [109]:
indices_1=np.array([0,2,4])  # creamos el array de índices
w[indices_1]

array([10, 30, 50])

Obtenga los elementos que se encuentran en las posiciones segunda, cuarta y octava de w

In [43]:
# Escriba aquí su código
indices_2=np.array([1,3,7])
w[indices_2]

array([20, 40, 80])

Por supuesto que no era necesario crear primero el array de índices, hubiera bastado con hacer:

In [111]:
w[[1,3,7]]

array([20, 40, 80])

In [22]:
# quiero el 2do, 5to y 7mo elemento:
w[[1,4,6]]

array([20, 50, 70])

### Uso de **[     ]** con matrices o arrays de 2 ejes (bidimensionales)

Para acceder a una posición dentro de un array se utilizan los corchetes 

**[ posición del elemento en cada eje separado por comas ]**  

M[0:3,1]

Para el caso de las matrices es decir los arrays con 2 ejes deberemos indicar la posición del elemento en cada uno de los ejes.  
$$M=\begin{bmatrix} 3 & 1 & -1 & 4\\ 2 & 5 & 1 & 2\\ 0 & 2 & 4 & 1 \end{bmatrix}$$

**M[ fila, columna ]**  
(recuerde que a diferencia del álgebra, aquí el primer elemento es el 0)


Para acceder al primer elemento, el número 3, deberemos indicar que está en la fila 0 y en la columna 0:  

**M[0,0]** 



In [44]:
M[0,0]

3

In [45]:
M[0,2]

-1

Obtenga el 5 de la matriz M

In [46]:
# Escriba aquí su código
M[1,1]

5

Supongamos que queremos obtener toda una una fila de M, digamos la primer fila (la fila número 0).  
Deberíamos indicar algo como esto:  
M[ número de fila deseada, todas las columnas]

Entonces para obtener la fila 0 podríamos escribir:

In [47]:
M[0,:]

array([ 3,  1, -1,  4])

Que es una nomenclatura bastante explícita, también soporta una nomenclatura como la siguiente, pero no la recomendamos.

In [48]:
M[0,]

array([ 3,  1, -1,  4])

Cómo obtendría la segunda fila?

In [50]:
# Escriba aquí su código
M[1,:]          

array([2, 5, 1, 2])

Cómo obtendría la última fila, sin importar cuántas filas tuviera la matriz?

In [51]:
# Escriba aquí su código
M[-1, :]

array([0, 2, 4, 1])

Cómo obtendría las dos primeras filas?

In [56]:
# Escriba aquí su código

M[0:2,:] 

array([[ 3,  1, -1,  4],
       [ 2,  5,  1,  2]])

La primer y tercer filas?

In [55]:
# Escriba aquí su código
M[[0,2], :]

array([[ 3,  1, -1,  4],
       [ 0,  2,  4,  1]])

Ahora practiquemos un poco con las columnas:  

$$M=\begin{bmatrix} 3 & 1 & -1 & 4\\ 2 & 5 & 1 & 2\\ 0 & 2 & 4 & 1 \end{bmatrix}$$
Obtenga la primer columna de M

In [59]:
# Escriba aquí su código
M[:,0]

array([3, 2, 0])

**Nota:** Observe que no presenta el resultado como una "columna", sino como un array de un solo eje.

La segunda y tercer columnas?

In [63]:
# Escriba aquí su código
M[:,[1,2]]

array([[ 1, -1],
       [ 5,  1],
       [ 2,  4]])

La segunda y la cuarta columnas?

In [64]:
# Escriba aquí su código
M[:,[1,3]]

array([[1, 4],
       [5, 2],
       [2, 1]])