# COMPUTACIÓN CIENTÍFICA
# PARCIAL 1

Prof. Ricardo Piña



## INDICACIONES:

- Para resolver puede utilizar más de una celda si es necesario.  
- Escriba comentarios con # para facilitar la lectura de las operaciones que realiza. 

**ENVÍO DEL EXAMEN**

Debe subir este archivo junto con el que se pide en uno de los ejericicos en el Aula Virtual de la materia a través del servicio de **MENSAJERÍA** (**no** lo haga a través del Lugar de Encuentro!).



## Ej 1:
Importe la librería numpy y llámela np

In [1]:
# Escriba aquí su código
import numpy as np


## Ej 2: vectores
Cree los siguientes vectores:
$ u= [1,5,-3]$ y $ v=[2,-1,3]$

In [2]:
# Escriba aquí su código
u=np.array([1,5,-3])
v=np.array([2,-1,3])
u,v



(array([ 1,  5, -3]), array([ 2, -1,  3]))

Calcule:  

$ w1= 3 u - 4 v$    

In [3]:
# Escriba aquí su código
w1=(3*u)-(4*v)
w1


array([ -5,  19, -21])

Calcule:  

$ w2=|u| $  (w2 = módulo o norma del vector u)

In [4]:
# Escriba aquí su código
w2=np.linalg.norm(u)
w2


5.916079783099616

Calcule:  
    
d= distancia entre u y v    

In [8]:
# Escriba aquí su código
d=np.linalg.norm(u-v)
d


8.54400374531753

Sea u1 el vector formado por todos los números pares desde el 2 hasta el 100 ambos inclusive:
Sea v1 el vector formado por todos los números impares desde el 1 hasta el 99, ambos inclusive.

Calcule:  

d1= distancia entre u1 y v1

In [13]:
# Escriba aquí su código
u1=np.arange(2,101,2)
v1=np.arange(1,100,2)
d1=np.linalg.norm(u1-v1)
d1

7.0710678118654755

Calcule el ángulo (en grados) entre u1 y v1 (no importa el orden)

In [14]:
# Escriba aquí su código
import math

cos_u1v1=(u1@v1/(np.linalg.norm(u1) * np.linalg.norm(v1)))
angulo=np.rad2deg(math.acos(cos_u1v1))
angulo

0.4888015776614167

## Ej 3: Matrices

Cree las matrices:  

$M=\begin{bmatrix} 2 & 1 & 4 \\ -3 & 0 & 5  \end{bmatrix}$  
$N=\begin{bmatrix} -2 & 1 \\ 0 & 3 \\ 1 & 4    \end{bmatrix}$ 

In [23]:
# Escriba aquí su código
M=np.array([[2,1,4],[-3,0,5]])
N=np.array([[-2,1],[0,3],[1,4] ])
M,N


(array([[ 2,  1,  4],
        [-3,  0,  5]]),
 array([[-2,  1],
        [ 0,  3],
        [ 1,  4]]))

Calcule: 

$ Q1 = (MN)^{-1} $   Nota: la potencia -1 indica inversa.

In [31]:
# Escriba aquí su código
Q1=np.linalg.inv(M@N)
Q1


array([[-0.07359307,  0.09090909],
       [ 0.04761905,  0.        ]])

Calcule:  
    
$ Q2=(M^T N^T)^{-1}    $  el superíndice T significa Transpuesta

In [35]:
# Escriba aquí su código 
T_M=M.T
T_N=N.T
Q2=np.linalg.inv(T_M@T_N)
print (T_M)
print (T_N)
#Dice que es una matriz singular lo cual significa que su determinante es 0, su inversa no existe

LinAlgError: Singular matrix

Obtenga en Q2f2 los elementos de la 2da fila de Q2, guárdelos con el nombre Q2f2.

In [36]:
# Escriba aquí su código

Q2f2=Q2[1,:]
Q2f2


array([0.04761905, 0.        ])

Obtenga en Q2c3 los elementos de la 3era columna de Q2

In [37]:
# Escriba aquí su código
Q2c3=Q2[2,:]
Q2c3
#No existe la 3°columna, es de 2x2

IndexError: index 2 is out of bounds for axis 0 with size 2

## Ej 4:


Cree la matriz P de números aleatorios (entre 0 y 1) de 100 filas x 200 columnas. Use el valor 123 como semilla para generar los números aleatorios:

In [46]:
np.random.seed([123])
P=np.random.random((100,200))
P

array([[0.0523636 , 0.08718668, 0.40724176, ..., 0.97723044, 0.06244219,
        0.41472736],
       [0.5004748 , 0.82935774, 0.17487868, ..., 0.19872546, 0.63490555,
        0.07060848],
       [0.20534254, 0.35826717, 0.77802059, ..., 0.98295666, 0.50013334,
        0.00524097],
       ...,
       [0.87015635, 0.81021275, 0.6305062 , ..., 0.93621331, 0.27831429,
        0.19792022],
       [0.27851747, 0.82886978, 0.27330643, ..., 0.75915012, 0.79522134,
        0.16510142],
       [0.02379909, 0.88262543, 0.95454404, ..., 0.15830329, 0.10762187,
        0.62745324]])

Guarde en la variable P_min el menor valor entre todos los elementos de la matriz P:

In [39]:
# Escriba aquí su código

P_min=np.min(P)
P_min

0.000239282013319575

Cuál es el mayor valor de **cada una de las columnas** de P? Guarde los valores en P_max

In [41]:
# Escriba aquí su código
P_max=np.max(P,axis=0)
P_max

array([0.99123952, 0.99941712, 0.98883578, 0.96466313, 0.99058377,
       0.99925577, 0.99513287, 0.98597416, 0.99694696, 0.98889057,
       0.99171373, 0.98048886, 0.99012136, 0.98311004, 0.99509114,
       0.99991334, 0.99909995, 0.99595976, 0.99980032, 0.99602113,
       0.98599192, 0.97532431, 0.99983112, 0.99701582, 0.99946921,
       0.99917748, 0.99856616, 0.99607313, 0.99601996, 0.98309252,
       0.99475208, 0.99237893, 0.97735245, 0.99813423, 0.99991827,
       0.99199295, 0.97829756, 0.9984189 , 0.99839458, 0.96877687,
       0.98985086, 0.99181211, 0.98532788, 0.99463278, 0.99469361,
       0.99723952, 0.99860248, 0.99252168, 0.99025782, 0.99194878,
       0.99655271, 0.98925499, 0.96751841, 0.99968502, 0.99865633,
       0.99891284, 0.976408  , 0.99840458, 0.9846753 , 0.99330268,
       0.98651446, 0.99938513, 0.99889203, 0.97763867, 0.99990416,
       0.99757188, 0.97481909, 0.99684381, 0.98983085, 0.97305982,
       0.99679431, 0.99358842, 0.99968643, 0.99733061, 0.96905

Guarde en la variable n1 la cantidad de elementos de P cuyo valor es menor o igual que 0.3

In [43]:
# Escriba aquí su código
n1=np.sum(P<=0.3)
n1


6000

Cuál es el valor promedio de todos los elementos de P? Guardelo en P_prom

In [48]:
# Escriba aquí su código

P_prom=np.mean(P)
P_prom

0.5012615985096821

Cuántos elementos de P son mayores que dicho promedio? Guarde el resultado en P_may

In [90]:
# Escriba aquí su código
P_may=np.sum(P>P_prom)
P_may




10014

En cuántas columnas de P su promedio está por debajo del promedio de toda la matriz? Guarde en valor en n_menor

In [50]:
# Escriba aquí su código
prom_col=np.mean(P,axis=0)
n_menor=np.sum(prom_col<P_prom)
n_menor



102

Cuántos valores de P son mayores o iguales que 0.2 y menores o iguales que 0.8? Guarde el resultado en la variable n2

In [51]:
# Escriba aquí su código

n2=np.sum(np.logical_and(P>=0.2,P<=0.8))
n2

11877

Cree la matriz P1, que se obtiene reemplazando todos los valores P que son menores o iguales que 0.5 por el valor 0 y reemplazando todos los valores mayores que 0.5 por el valor 1

In [63]:
# Escriba aquí su código
P1=np.logical_and(np.where(P<=0.5,P,0), np.where(P>=0.5,P,1))
P1



array([[ True,  True,  True, ..., False,  True,  True],
       [False, False,  True, ...,  True, False,  True],
       [ True,  True, False, ..., False, False,  True],
       ...,
       [False, False, False, ..., False,  True,  True],
       [ True, False,  True, ..., False, False,  True],
       [ True, False, False, ...,  True,  True, False]])

Guarde esta matriz con el nombre P1 y luego guárdela también en un archivo de numpy de nombre *P1.npy* (no se olvide de adjuntarme dicho archivo cuando me envíe el examen)


In [96]:
# Escriba aquí su código

np.save("P1.npy",P1)

Cree la matriz P2 formada sólo por las columnas pares de P1 es decir las columnas de **índice** 0,2,4,...

In [103]:
# Escriba aquí su código
P2=np.array(P[:,1:2])
P2


array([[0.08718668],
       [0.82935774],
       [0.35826717],
       [0.35018207],
       [0.2313023 ],
       [0.97054366],
       [0.75225332],
       [0.87263142],
       [0.81640885],
       [0.20241718],
       [0.38977423],
       [0.09096382],
       [0.37563952],
       [0.58940642],
       [0.96233735],
       [0.51101744],
       [0.17618003],
       [0.83938993],
       [0.7363658 ],
       [0.95475918],
       [0.61451306],
       [0.83040998],
       [0.48849574],
       [0.52206798],
       [0.23416413],
       [0.57569478],
       [0.00337108],
       [0.93025378],
       [0.26617372],
       [0.63126874],
       [0.01169769],
       [0.95704721],
       [0.75462647],
       [0.56854924],
       [0.48936467],
       [0.53382045],
       [0.18949551],
       [0.21336535],
       [0.08521471],
       [0.6999607 ],
       [0.16405521],
       [0.09697456],
       [0.39257954],
       [0.90761121],
       [0.08840755],
       [0.4385833 ],
       [0.30977502],
       [0.694

# Respuestas - Resumen

## Rtas Ej 2

In [68]:

u


array([ 1,  5, -3])

In [69]:
v

array([ 2, -1,  3])

In [70]:
w1

array([ -5,  19, -21])

In [71]:
w2

5.916079783099616

In [72]:
d

8.54400374531753

In [73]:
d1

7.0710678118654755

## Rtas Ej 3

In [74]:
M

array([[ 2,  1,  4],
       [-3,  0,  5]])

In [75]:
N

array([[-2,  1],
       [ 0,  3],
       [ 1,  4]])

In [76]:
Q1

array([[-0.07359307,  0.09090909],
       [ 0.04761905,  0.        ]])

In [77]:
Q2

array([[-0.07359307,  0.09090909],
       [ 0.04761905,  0.        ]])

In [78]:
Q2f2

array([0.04761905, 0.        ])

In [79]:
Q2c3

NameError: name 'Q2c3' is not defined

## Rtas Ej 4

In [85]:
P


array([[0.0523636 , 0.08718668, 0.40724176, ..., 0.97723044, 0.06244219,
        0.41472736],
       [0.5004748 , 0.82935774, 0.17487868, ..., 0.19872546, 0.63490555,
        0.07060848],
       [0.20534254, 0.35826717, 0.77802059, ..., 0.98295666, 0.50013334,
        0.00524097],
       ...,
       [0.87015635, 0.81021275, 0.6305062 , ..., 0.93621331, 0.27831429,
        0.19792022],
       [0.27851747, 0.82886978, 0.27330643, ..., 0.75915012, 0.79522134,
        0.16510142],
       [0.02379909, 0.88262543, 0.95454404, ..., 0.15830329, 0.10762187,
        0.62745324]])

In [81]:
P_min

0.000239282013319575

In [87]:
P_max

array([0.99123952, 0.99941712, 0.98883578, 0.96466313, 0.99058377,
       0.99925577, 0.99513287, 0.98597416, 0.99694696, 0.98889057,
       0.99171373, 0.98048886, 0.99012136, 0.98311004, 0.99509114,
       0.99991334, 0.99909995, 0.99595976, 0.99980032, 0.99602113,
       0.98599192, 0.97532431, 0.99983112, 0.99701582, 0.99946921,
       0.99917748, 0.99856616, 0.99607313, 0.99601996, 0.98309252,
       0.99475208, 0.99237893, 0.97735245, 0.99813423, 0.99991827,
       0.99199295, 0.97829756, 0.9984189 , 0.99839458, 0.96877687,
       0.98985086, 0.99181211, 0.98532788, 0.99463278, 0.99469361,
       0.99723952, 0.99860248, 0.99252168, 0.99025782, 0.99194878,
       0.99655271, 0.98925499, 0.96751841, 0.99968502, 0.99865633,
       0.99891284, 0.976408  , 0.99840458, 0.9846753 , 0.99330268,
       0.98651446, 0.99938513, 0.99889203, 0.97763867, 0.99990416,
       0.99757188, 0.97481909, 0.99684381, 0.98983085, 0.97305982,
       0.99679431, 0.99358842, 0.99968643, 0.99733061, 0.96905

In [83]:
n1

6000

In [88]:
P_prom

0.5012615985096821

In [91]:
P_may

10014

In [92]:
n_menor

102

In [93]:
n2

11877

In [94]:
P1

array([[ True,  True,  True, ..., False,  True,  True],
       [False, False,  True, ...,  True, False,  True],
       [ True,  True, False, ..., False, False,  True],
       ...,
       [False, False, False, ..., False,  True,  True],
       [ True, False,  True, ..., False, False,  True],
       [ True, False, False, ...,  True,  True, False]])

In [95]:
P2

array([[0.08718668],
       [0.82935774],
       [0.35826717],
       [0.35018207],
       [0.2313023 ],
       [0.97054366],
       [0.75225332],
       [0.87263142],
       [0.81640885],
       [0.20241718],
       [0.38977423],
       [0.09096382],
       [0.37563952],
       [0.58940642],
       [0.96233735],
       [0.51101744],
       [0.17618003],
       [0.83938993],
       [0.7363658 ],
       [0.95475918],
       [0.61451306],
       [0.83040998],
       [0.48849574],
       [0.52206798],
       [0.23416413],
       [0.57569478],
       [0.00337108],
       [0.93025378],
       [0.26617372],
       [0.63126874],
       [0.01169769],
       [0.95704721],
       [0.75462647],
       [0.56854924],
       [0.48936467],
       [0.53382045],
       [0.18949551],
       [0.21336535],
       [0.08521471],
       [0.6999607 ],
       [0.16405521],
       [0.09697456],
       [0.39257954],
       [0.90761121],
       [0.08840755],
       [0.4385833 ],
       [0.30977502],
       [0.694