<h1>Tabla de Contenidos<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#SITUACIÓN-PROFESIONAL-1" data-toc-modified-id="SITUACIÓN-PROFESIONAL-1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>SITUACIÓN PROFESIONAL 1</a></span><ul class="toc-item"><li><span><a href="#CLASE-1" data-toc-modified-id="CLASE-1-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>CLASE 1</a></span><ul class="toc-item"><li><span><a href="#Prof.-Ricardo-Piña" data-toc-modified-id="Prof.-Ricardo-Piña-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Prof. Ricardo Piña</a></span></li></ul></li></ul></li><li><span><a href="#Listas-y-Arrays" data-toc-modified-id="Listas-y-Arrays-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Listas y Arrays</a></span></li><li><span><a href="#Arrays-con-Numpy" data-toc-modified-id="Arrays-con-Numpy-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Arrays con Numpy</a></span><ul class="toc-item"><li><span><a href="#Creación-de-arrays-en-NumPy" data-toc-modified-id="Creación-de-arrays-en-NumPy-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Creación de arrays en NumPy</a></span></li><li><span><a href="#Describiendo-arrays:-.ndim,-.shape,-.size" data-toc-modified-id="Describiendo-arrays:-.ndim,-.shape,-.size-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Describiendo arrays: .ndim, .shape, .size</a></span></li></ul></li><li><span><a href="#EJERCICIOS" data-toc-modified-id="EJERCICIOS-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>EJERCICIOS</a></span></li><li><span><a href="#Operaciones-con-arrays-en-NumPy" data-toc-modified-id="Operaciones-con-arrays-en-NumPy-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Operaciones con arrays en NumPy</a></span><ul class="toc-item"><li><span><a href="#Suma-de-vectores" data-toc-modified-id="Suma-de-vectores-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Suma de vectores</a></span></li><li><span><a href="#Producto-de-un-vector-por-un-escalar" data-toc-modified-id="Producto-de-un-vector-por-un-escalar-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Producto de un vector por un escalar</a></span></li><li><span><a href="#Producto-interno-o-producto-punto-de-vectores" data-toc-modified-id="Producto-interno-o-producto-punto-de-vectores-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Producto interno o producto punto de vectores</a></span></li><li><span><a href="#Producto-vectorial-de-dos-vectores-o-producto-cruz" data-toc-modified-id="Producto-vectorial-de-dos-vectores-o-producto-cruz-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Producto vectorial de dos vectores o producto cruz</a></span></li><li><span><a href="#Módulo-o-norma-de-un-vector" data-toc-modified-id="Módulo-o-norma-de-un-vector-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Módulo o norma de un vector</a></span></li><li><span><a href="#Distancia-entre-dos-vectores-o-dos-puntos" data-toc-modified-id="Distancia-entre-dos-vectores-o-dos-puntos-5.6"><span class="toc-item-num">5.6&nbsp;&nbsp;</span>Distancia entre dos vectores o dos puntos</a></span></li></ul></li><li><span><a href="#EJERCICIOS" data-toc-modified-id="EJERCICIOS-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>EJERCICIOS</a></span><ul class="toc-item"><li><span><a href="#Operaciones-elemento-a-elemento-o-element---wise-operations" data-toc-modified-id="Operaciones-elemento-a-elemento-o-element---wise-operations-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Operaciones elemento a elemento o element - wise operations</a></span></li><li><span><a href="#Cuidado:-element---wise-product" data-toc-modified-id="Cuidado:-element---wise-product-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Cuidado: element - wise product</a></span></li></ul></li></ul></div>

![IES21](img/logo_ies.png)

# COMPUTACIÓN CIENTÍFICA
## SITUACIÓN PROFESIONAL 1
### CLASE 1
#### Prof. Ricardo Piña

# Algebra en Python: Numpy

## Listas y Arrays

Uno de los tipos de datos soportados nativamente en Python son las **listas**. Por ejemplo la siguiente es una lista:

(SHIFT + ENTER para ejecutar una celda)

In [1]:
lista01=[1,2,3,4]
lista01

[1, 2, 3, 4]

En álgebra Ud ha trabajado con **vectores** y es habitual que uno tienda a pensar que las listas son vectores, pero no lo son.

Las listas pueden contener elementos de distinto tipo, por ejemplo, texto o números y los vectores que aprendió a usar en álgebra son numéricos.

In [4]:
lista02=[1, "árbol",2,"casa"]
print(lista02)

[1, 'árbol', 2, 'casa']


Pero a veces tenemos listas que contienen sólo valores numéricos y podemos confundirnos. En estos casos suelen ocurrir cosas inesperadas como la siguiente:

In [5]:
lista03=[5,5,5,5]

In [9]:
print(lista01)
print(lista03)

[1, 2, 3, 4]
[5, 5, 5, 5]


In [10]:
lista01+lista03

[1, 2, 3, 4, 5, 5, 5, 5]

Seguramente no fue el resultado esperado, al sumar dos listas, creó una nueva lista, más larga, con los elementos de la segunda lista a continuación de la primera.  
Obviamente este comportamiento de las listas puede ser muy útil, pero ahora queremos aplicar Python para resolver problemas de álgebra. 

## Arrays con Numpy

Numpy es una de las librerías matemáticas más usadas en Python y la que da origen a otras aún más sofisticadas. Incorpora algoritmos que permiten resolver operaciones algebraicas en forma **eficiente** porque están precompiladas en C. 
Veamos cómo trabajar con Numpy.

La estructura principal en NumPy es el **array multidimensional homogéneo**.  

Aclaremos un poco:  

**Homogéneo** significa que todos los elementos son del mismo tipo, para nosotros, generalmente serán números, ésto no nos traerá problemas.    



**Dimensional o multidimensional** es un término algo confuso ya que se superpone con la definición de dimensión que aprendimos en álgebra!  

Por ejemplo, en álgebra un punto en el plano se representa como un vector de dimensión 2, es decir que se puede escribir como  

(1,4)  

si lo escribimos como un vetor fila, o como:  

$$\begin{pmatrix} 1 \\ 4 \end{pmatrix}$$  

si lo escribimos como un vector columna.

A un punto en el espacio tridimensional lo podemos representar como un vector de dimensión 3, por ejemplo:  

(2,1,4)  

o como:  

$$\begin{pmatrix} 2 \\ 1 \\  4  \end{pmatrix}$$


si lo escribimos como vector columna. 



En cambio en la nomenclatura de NumPy todos los vectores son de **"dimensión 1"**.  

Quiénes tienen dimensión 2 en la nomenclatura de NumPy?  
- Lo que en álgebra conocemos como **matrices**.  

Ahora debe quedar claro el por qué, fíjese en la disposición de los elementos de una matriz:  

$$\begin{bmatrix} 1 & 2 & -1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$  

Podemos observar que los elementos de la matriz se disponen en dos direcciones, una horizontal y otra vertical, por eso en NumPy se dice que las matrices son de "dimensión 2". En cambio los elementos de los vectores se disponen en una sola dirección y por eso en NumPy se dice que son de "dimensión 1".





A veces se utiliza una nomenclatura que resulta más clara para los elementos de NumPy y en vez de usar la palabra dimensión se utiliza la palabra **axis o eje**. 

Entonces en NumPy:  

- un array de un eje (o dimensión 1 en NumPy)   es lo que en álgebra denominamos **vector**
- un array de 2 ejes (o dimensión 2 en NumPy) es lo que en álgebra definimos como **matriz**
- un array de más ejes (o mayor dimensión en NumPy) es lo que en álgebra se define como **tensor**

Si desde el punto de vista de NumPy todos los vectores tienen un eje (o son de dimensión 1), qué distingue al vector (1,2) del (2,1,4) ?  

La cantidad de elementos que tienen!  

- la cantidad de elementos de (1,2) es 2 y   
- la cantidad de elementos de (2,1,4) es 3

En NumPy la cantidad de elementos se denomina con **length**.

Así por ejemplo en  lo que cambia es su "length" o longitud.

### Creación de arrays en NumPy

A diferencia de las listas que comentamos al principio, los arrays deben definirse como tales, vamos a crear un vector, es decir un array con un solo eje o axis o de "dimensión uno".  
 

Para crear el array usamos:  

**np.array()**  

y dentro del paréntesis los elementos se enumeran como una **secuencia** entre corchetes y separados por coma:  

**np.array([ secuencia de elementos separados por coma ])**

Podemos pensar que de esta manera NumPy crea vectores fila. 

Creemos el vector (1,2,3)

Lo primero que debemos hacer es importar Numpy.

In [6]:
import numpy as np              # el alias np es frecuentemente utilizado para abreviar la nomenclatura de numpy

In [7]:
vector_1=np.array([1,2,3])

Veamos qué creó

In [11]:
vector_1

array([1, 2, 3])

Observe que en la salida nos indica que es un array.
Pero si lo ponemos dentro de un print()

In [41]:
print(vector_1)

[1 2 3]


In [ ]:
sólo nos muestra el resultado.

Ahora vamos a crear una **matriz**.
Desde el punto de vista de NumPy una matriz será una secuencia de vectores, y un vector era una secuencia de números ...


np.array([ [ fila 1 ],[ fila 2 ],...,[ fila n ] ])

Creemos la matriz  

$$\begin{bmatrix} 1 & 2 & -1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \\ 1 & 5 & 3\end{bmatrix}$$  

In [16]:
matriz_1=np.array([[1,2,-1],[3,0,1],[0,2,4],[1,5,3]])

In [17]:
matriz_1

array([[ 1,  2, -1],
       [ 3,  0,  1],
       [ 0,  2,  4],
       [ 1,  5,  3]])

In [46]:
print(matriz_1)

[[ 1  2 -1]
 [ 3  0  1]
 [ 0  2  4]
 [ 1  5  3]]


### Describiendo arrays: .ndim, .shape, .size 

La propiedad .ndim nos indica la cantidad de ejes (o dimensiones) que tiene el array:

Cuántos ejes tiene matriz_1?
$$\begin{bmatrix} 1 & 2 & -1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \\ 1 & 5 & 3\end{bmatrix}$$  

In [19]:
matriz_1.ndim

2

Cuántos ejes tiene vector_1  (1,2,3) ?

In [20]:
vector_1.ndim

1

La propiedad .shape nos indica la cantidad de elementos en cada eje, si es una matriz nos indicará la cantidad de filas y de columnas que tiene. 

In [55]:
matriz_1.shape

(4, 3)


In [56]:
vector_1.shape

(3,)


La propiedad .size nos indica la cantidad de elementos en total que tiene el array:

In [21]:
matriz_1.size

12

In [22]:
vector_1.size

3

## EJERCICIOS

1) Cree el vector_2 = (1,2,3,4,5)

In [2]:
# Escriba a continuación su código para crear vector_2

import numpy as np

vector_2= np.array([1,2,3,4,5])

# Escriba a continuación el código para mostrar vector_2

print(vector_2)

[1 2 3 4 5]


2) Cuál es la dimensión **algebraica** de vector_2?

Rta: Dimensión 5

3) Cuál es la dimensión **"informática o de NumPy"** de vector_2?

In [3]:
# Escriba a continuación el código para responder la pregunta anterior
vector_2.ndim



1

4) Cuántos elementos tiene vector_2?

In [5]:
# Escriba a continuación el código para responder la pregunta anterior

vector_2.shape
vector_2.size

5

5) Cree la matriz_2 
$$\begin{bmatrix} 3 & 1 & -1 & 4\\ 2 & 5 & 1 & 2\\ 0 & 2 & 4 & 1 \end{bmatrix}$$  

In [7]:
# Escriba a continuación su código para crear matriz_2

import numpy as np

matriz_2= np.array([[3,1,-1,4],[2,5,1,2],[0,2,4,1]])

# Escriba a continuación el código para mostrar matriz_2

matriz_2




array([[ 3,  1, -1,  4],
       [ 2,  5,  1,  2],
       [ 0,  2,  4,  1]])

6) Cuántos ejes tiene matriz_2? (o cuál es la dimensión informática de matriz 2?

In [8]:
# Escriba a continuación el código para responder la pregunta anterior
matriz_2.ndim


2

7) Cuántas filas y cuántas columnas tiene matriz_2?

In [9]:
# Escriba a continuación el código para responder la pregunta anterior
matriz_2.shape


(3, 4)

8) Cuántos elementos en total tiene matriz_2?

In [10]:
# Escriba a continuación el código para responder la pregunta anterior
matriz_2.size


12

## Operaciones con arrays en NumPy

### Suma de vectores

Tanto para sumar o restar vectores podemos utilizar los símbolos habituales + y - 

Si queremos sumar los vectores v1 = (1,2,3)  y v2 = (2,0,-4)

In [83]:
v1=np.array([1,2,3])
v2=np.array([2,0,-4])

v1+v2

array([ 3,  2, -1])

Nota: si desea sumar o restar vectores con distinta cantidad de elementos, dará error.

### Producto de un vector por un escalar

También podemos usar el símbolo habitual para producto que en Python es el asterisco *.  

Por ejemplo, si queremos efectuar 5v1, podemos realizar:

In [75]:
5*v1

array([ 5, 10, 15])

Para realizar 1/5 v1

In [76]:
1/5*v1

array([0.2, 0.4, 0.6])

In [ ]:
También podemos hacer: 

In [77]:
v1/5

array([0.2, 0.4, 0.6])

### Producto interno o producto punto de vectores

El producto interno de dos vectores puede realizarse de dos maneras:  

- con la función:  np.dot(vector1, vector2)
- con el operador @, vector1 @ vector2  

Veamos:

In [87]:
print(v1)
print(v2)

np.dot(v1,v2)

[1 2 3]
[ 2  0 -4]


-10

In [88]:
print(v1)
print(v2)

v1 @ v2

[1 2 3]
[ 2  0 -4]


-10

### Producto vectorial de dos vectores o producto cruz

Se puede utilizar la función np.cross(v1,v2)

In [89]:
print(v1)
print(v2)

np.cross(v1,v2)

[1 2 3]
[ 2  0 -4]


array([-8, 10, -4])

### Módulo o norma de un vector

En álgebra se define el Módulo o norma de un vector como un número positivo que representa la longitud del mismo.

Si el vector es $ u=(u_1,u_2,...,u_n)$

Su módulo o norma se calcula como:

$$||u||=\sqrt[]{u^2_1+u^2_2+...+u^2_n}$$  

Si lo pensamos un poco, calcular la norma de un vector con los métodos de programación tradicionales requiere efectuar algún loop recorriendo todos los elementos del vector, elevándolos al cuadrado, sumándolos a un acumulador y luego de recorrer todo el vector deberíamos calcular su raíz cuadrada.  

Un poco pesado, por suerte pensando algebraicamente y usando NumPy tenemos opciones muy sencillas que nos permitirán focalizarnos en las operaciones matemáticas y no en la programación en sí. 




El módulo de un vector se podía calcular también como la raíza cuadrada del producto interno del vector con sí mismo:

$$ ||u||=\sqrt[]{u . u} $$


Entonces podríamos calcular el módulo del vecto v1 como:

In [108]:
np.sqrt(v1@v1)

3.7416573867739413

Bastante más sencillo, no es cierto?

Pero además, dentro de NumPy existe una librería dedicada a operaciones específicas de álgebra lineal denominada **linalg**, y entre ellas se encuentra el cáclulo del módulo o norma de un vector, así que podemos efectuar el cálculo en forma más elegante y legible para quien lee el código:


In [109]:
np.linalg.norm(v1)

3.7416573867739413

### Distancia entre dos vectores o dos puntos

En álgebra se define la distancia (euclídea) entre dos puntos o entre 2 vectores como el módulo o norma de su diferencia:  

distancia(u,v) = ||u-v||  

Se anima a calcular la distancia entre los vectores v1 y v2 que definimos con anterioridad?

Resuelva el problema primero manualmente con papel y lápiz ... y luego en la celda siguiente

In [12]:
# Escriba en esta celda su código
import numpy as np
v1=np.array([1,2,3])
v2=np.array([2,0,-4])
np.linalg.norm(v1-v2)

7.3484692283495345

## EJERCICIOS

Supongamos que tenemos la intención de crear un **Sistema de Recomendaciones** para los clientes de nuestro servicio de streaming de películas.  

Para ello, decidimos recabar información de nuestros clientes, por ejemplo le solicitamos que califique qué tanto le gustó cada película después de que la vio.  

Elaboramos un ranking de 1 a 5 siendo 1 que le gustó poco y 5 que le gustó muchísimo.  

Después de un tiempo tendremos el puntaje asignado a muchas películas por muchos clientes.  
Supongamos que nuestros clientes son A,B,C,D, etc y las películas son P1,P2, P3, nuestra información podría verse como en la siguiente tabla.


Nuestro objetivo es determinar si le recomendamos o no al cliente D la P4.  

Nuestra hipótesis es que el gusto del cliente D será similar al del cliente que haya calificado más parecido a D las películas P1, P2 y P3, es decir al cliente más cercano a D considerando sólo las películas de 1 a 3.  

Entonces crearemos un vector para cada cliente con las calificaciones que dio para las películas 1 a 3 y calcularemos la distancia entre el vector del cliente D y cada uno de los otros clientes. 

Esto nos permitirá determinar cuál de los clientes A, B o C es el más cercano a D, y asumiremos que el cliente D tendrá una calificación de P4 parecida al del más cercano a él.


In [119]:
# Cree aquí los vectores considerando sólo las películas P1 a P3 para los cuatro clientes
import numpy as np
cliente_a= np.array([5,1,3])
cliente_b= np.array([3,5,4])
cliente_c= np.array([1,3,5])
cliente_d= np.array([4,2,1])

In [14]:
#Calcule la distancia entre el vector del cliente D y el cliente A
import numpy as np
cliente_a= np.array([5,1,3])
cliente_d= np.array([4,2,1])
np.linalg.norm(cliente_d-cliente_a)

2.449489742783178

In [15]:
#Calcule la distancia entre el vector del cliente D y el cliente B
import numpy as np
cliente_b= np.array([3,5,4])
cliente_d= np.array([4,2,1])
np.linalg.norm(cliente_d-cliente_b)

4.358898943540674

In [16]:
#Calcule la distancia entre el vector del cliente D y el cliente C
import numpy as np
cliente_c= np.array([1,3,5])
cliente_d= np.array([4,2,1])
np.linalg.norm(cliente_d-cliente_c)

5.0990195135927845

Cuál es el cliente más cercano a C4? En base a esta cercanía, cree que la P4 le gustará o no a C4?

Rta: El cliente mas cercano es el cliente A. Y segun lo que el cliente A puso para p4 (valor de 1), creo que al cliente D no le gustará.

### Operaciones elemento a elemento o element - wise operations 

Los arrays de NumPy también incluyen otras operaciones que no están definidas en álgebra, pero que pueden resultarnos de utilidad al programar. 

Por ejemplo, para calcular la potencia de un número en Python se utiliza doble asterisco **

In [92]:
5**2

25

In [93]:
5**3

125

NumPy permite aplicar esta operación a todos los elementos de un vector (o de un array en general)

In [94]:
print(v1)
v1**2

[1 2 3]


array([1, 4, 9], dtype=int32)

El mismmo concepto se aplica a operaciones como:  

- raíz cuadrada: np.sqrt()
- funciones trigonométricas como sin(), cos(), tan()
- exponenciales

In [96]:
print(v1)
np.sqrt(v1)

[1 2 3]


array([1.        , 1.41421356, 1.73205081])

In [99]:
print(v1)
np.sin(v1)      # toma los ángulos en radianes

[1 2 3]


array([0.84147098, 0.90929743, 0.14112001])

In [100]:
print(v1)
np.cos(v1)      # toma los ángulos en radianes

[1 2 3]


array([ 0.54030231, -0.41614684, -0.9899925 ])

In [101]:
print(v1)
np.tan(v1)      # toma los ángulos en radianes

[1 2 3]


array([ 1.55740772, -2.18503986, -0.14254654])

In [102]:
print(v1)
np.exp(v1)      

[1 2 3]


array([ 2.71828183,  7.3890561 , 20.08553692])

In [105]:
print(v1)
2**v1      

[1 2 3]


array([2, 4, 8], dtype=int32)

### Cuidado: element - wise product

Por ejemplo en álgebra no está definida la operación de "producto de dos vectores", pero en NumPy sí podemos multiplicarlos: 

Recordemos quiénes son v1 y v2 y veamos qué hace NumPy cuando los multiplicamos:

In [86]:
print(v1)
print(v2)

print(v1*v2)

[1 2 3]
[ 2  0 -4]
[  2   0 -12]


Observamos que el resultado es otro vector, cuyas componentes surgen de multiplicar componente a componente ambos vectores. 