<h1>Tabla de Contenidos<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#SITUACIÓN-PROFESIONAL-1" data-toc-modified-id="SITUACIÓN-PROFESIONAL-1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>SITUACIÓN PROFESIONAL 1</a></span><ul class="toc-item"><li><span><a href="#CLASE-3" data-toc-modified-id="CLASE-3-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>CLASE 3</a></span><ul class="toc-item"><li><span><a href="#Prof.-Ricardo-Piña" data-toc-modified-id="Prof.-Ricardo-Piña-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Prof. Ricardo Piña</a></span></li></ul></li></ul></li><li><span><a href="#Arrays-especiales" data-toc-modified-id="Arrays-especiales-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Arrays especiales</a></span><ul class="toc-item"><li><span><a href="#Vector-formada-por-unos" data-toc-modified-id="Vector-formada-por-unos-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Vector formada por unos</a></span></li><li><span><a href="#Matriz-formada-por-unos" data-toc-modified-id="Matriz-formada-por-unos-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Matriz formada por unos</a></span></li><li><span><a href="#Vector-formado-por-todos-sus-elementos-iguales" data-toc-modified-id="Vector-formado-por-todos-sus-elementos-iguales-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Vector formado por todos sus elementos iguales</a></span></li><li><span><a href="#Matriz-formada-por-todos-sus-elementos-iguales" data-toc-modified-id="Matriz-formada-por-todos-sus-elementos-iguales-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Matriz formada por todos sus elementos iguales</a></span></li><li><span><a href="#Vector-Nulo:-formado-por-ceros" data-toc-modified-id="Vector-Nulo:-formado-por-ceros-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Vector Nulo: formado por ceros</a></span></li><li><span><a href="#Matriz-Nula:--formada-por-ceros" data-toc-modified-id="Matriz-Nula:--formada-por-ceros-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Matriz Nula:  formada por ceros</a></span></li><li><span><a href="#Matriz-Identidad" data-toc-modified-id="Matriz-Identidad-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Matriz Identidad</a></span></li><li><span><a href="#Matriz-de-números-aleatorios" data-toc-modified-id="Matriz-de-números-aleatorios-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>Matriz de números aleatorios</a></span></li><li><span><a href="#Matriz-de-números-aleatorios-decimales" data-toc-modified-id="Matriz-de-números-aleatorios-decimales-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>Matriz de números aleatorios decimales</a></span></li><li><span><a href="#Matriz-de-números-aleatorios-enteros" data-toc-modified-id="Matriz-de-números-aleatorios-enteros-2.10"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>Matriz de números aleatorios enteros</a></span></li></ul></li><li><span><a href="#Creación-de-secuencias-útiles" data-toc-modified-id="Creación-de-secuencias-útiles-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Creación de secuencias útiles</a></span><ul class="toc-item"><li><span><a href="#numpy.arange" data-toc-modified-id="numpy.arange-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>numpy.arange</a></span></li></ul></li><li><span><a href="#Convertir-a-array" data-toc-modified-id="Convertir-a-array-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Convertir a array</a></span><ul class="toc-item"><li><span><a href="#numpy.reshape" data-toc-modified-id="numpy.reshape-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>numpy.reshape</a></span></li><li><span><a href="#Flatten" data-toc-modified-id="Flatten-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Flatten</a></span></li><li><span><a href="#Transpuesta-de-una-matriz" data-toc-modified-id="Transpuesta-de-una-matriz-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Transpuesta de una matriz</a></span></li></ul></li><li><span><a href="#Arrays-Booleanos" data-toc-modified-id="Arrays-Booleanos-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Arrays Booleanos</a></span></li><li><span><a href="#Truco" data-toc-modified-id="Truco-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Truco</a></span></li></ul></div>

![IES21](img/logo_ies.png)

# COMPUTACIÓN CIENTÍFICA
## SITUACIÓN PROFESIONAL 1
### CLASE 3
#### Prof. Ricardo Piña

# Algebra en Python: Numpy

In [2]:
import numpy as np

## Arrays especiales

Muchas veces necesitaremos crear matrices rápidamente, sin cargar uno por uno sus elementos, NumPy nos provee con varias alternativas para hacerlo.

### Vector formada por unos

In [3]:
np.ones(4)

array([1., 1., 1., 1.])

### Matriz formada por unos

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Cree una matriz de 4 filas y 6 columnas formada por unos.

In [1]:
# Escriba aquí su código
import numpy as np
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

Obviamente si necesitara una matriz formada toda por cincos, bastaría con multiplicar la matriz anterior por 5

In [2]:
# Escriba aquí su código

np.ones((4,6))*5

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

También es posible crear esta matriz usando:

### Vector formado por todos sus elementos iguales

In [7]:
np.full(3,5)

array([5, 5, 5])

### Matriz formada por todos sus elementos iguales

In [3]:
np.full((4,6),5)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

### Vector Nulo: formado por ceros

In [84]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

### Matriz Nula:  formada por ceros

In [85]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Matriz Identidad

Las matrices identidad son aquellas **matrices cuadradas** cuya **diagonal principal está formada por unos y el resto de sus elementos son todos ceros**.  

Por ejemplo la siguente es la matriz Identidad de orden 3 
$$I_3=\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$  

Para crear se utiliza la función np.eye(orden), dado que es una matriz cuadrada en orden sólo se indica un número.  
Por ejemplo para crear la matriz anterior:


In [86]:
I3=np.eye((3))
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Cree una matriz cuadrada de orden 5, cuya diagonal principal está formada por cuatros. 

In [13]:
# Escriba aquí su código
np.eye((5))*4



array([[4., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 4.]])

### Matriz de números aleatorios

Numpy provee de diversas funciones para obtener números aleatorios. 

Por ejemplo:  

*np.random.random([size])*  

devuelve una cantidad = size de números al azar entre [0,1[  (Nota: incluye al 0 pero **no** inlcuye al 1)


Obtenga una secuencia de 5 números aleatorios entre [0,1[ 

In [10]:
# Escriba aquí su código
np.random.random([5]) #En el corchete va la cantidad de numeros que quiero que me devuelva. el rango es enter 0 y 1

array([0.20990373, 0.7481791 , 0.81193441, 0.50651124, 0.42367739])

Observe que si ejecuta el código anterior los valores obtenidos serán distintos cada vez que ejecute.  
Si necesita que los números aleartorios generados sean siempre los mismos, por ejemplo para conseguir "repetibilidad" de un experimento, deberá primero crear una semilla (seed).  

Nota: En el caso de Jupyter el  valor de la seed se mantiene sólo dentro de la misma celda. Por las dudas, verifique.  


Por ejemplo, ejecute varias veces el siguiente código y observe si los números aleatorios generados son siempre los mismos. 

In [18]:
np.random.seed([123])
np.random.random((3))

array([0.0523636 , 0.08718668, 0.40724176])

A veces necesitamos generar números decimales (float) aleatorios en otro rango que no sea [0,1[  , en ese caso podemos usar random.uniform()  :

~~~
np.random.uniform(low=0.4, high=24.7, size=(10,))
~~~

In [90]:
np.random.uniform(low=0.4, high=24.7, size=(10,))

array([ 3.01711571, 22.29913273,  1.32713409, 13.42970957,  8.47240407,
       21.10570484,  4.27979624,  8.59436477,  8.51125239,  6.35746947])

Si necesitamos que sean números enteros: 

**randint(low[, high, size, dtype])**    

(nota: incluye a low, pero **no** incluye a high)

Por ejemplo si necesitamos 4 números enteros entre 1 y 10 (inclusive ambos)




In [91]:
np.random.randint(1,11,4)  

array([5, 5, 1, 4])

### Matriz de números aleatorios decimales

In [92]:
np.random.random((3,3))

array([[0.87863034, 0.37759478, 0.00659504],
       [0.73203925, 0.10203672, 0.04388745],
       [0.66713817, 0.1262497 , 0.90660798]])

Nuevamente, si necesitamos que los valores generados al azar sean los mismos cada vez que se ejecute la celda:

In [93]:
np.random.seed([49])
np.random.random((4,2))

array([[0.06688398, 0.41324282],
       [0.11050473, 0.75211146],
       [0.51128511, 0.04967399],
       [0.04480748, 0.73593439]])

### Matriz de números aleatorios enteros

In [94]:
np.random.randint(1,11,(3,3))

array([[5, 5, 8],
       [4, 1, 8],
       [1, 9, 7]])

## Creación de secuencias útiles

### numpy.arange
Supongamos que por algún motivo necesitamos crear una secuencia de números impares hasta el 100, hacerlo manualmente puede ser muy incómodo, pero tenemos la función arange.  
Su sintaxis es la siguiente:  


numpy.arange([start, ]stop, [step, ]dtype=None

(Consulte el Manual onlin de NumPy en: https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html )

- NumPy tomará como rango **desde el valor start inclusive** y se extenderá **hasta el valor step sin tomarlo**, es decir en el intervalo [start,stop[.  
- Por defecto inicia la secuencia en  0 con un step de 1 y determina el tipo de dato según los utilizados en la función


In [95]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Ahora podemos crear nuestra secuencia de números impares desde el 1 hasta el 100. (1,3,5 ....99)

In [96]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Ejercicio:  
Cree una secuencia de números desde el 1 hasta al 100 inclusive múltiplos de 10. (10, 20, 30, ..., 100)

In [21]:
# Escriba aquí su código

np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Cree la secuencia 1 ,1.2 ,1.4,1.6 ...5

In [22]:
np.arange(1,5.1,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

In [ ]:
También es posible crear secuencias descendentes, no olvide poner el salto o step con un valor negativo.
Cree el vector (10,9,8,..,1)

In [27]:
# Escriba aquí su código
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Convertir a array

### numpy.reshape

Muchas veces nos interesará poblar una matriz con números de alguna secuencia; en NumPy podemos transformar arrays con distinta cantidad de ejes entre sí. 

numpy.reshape(a, newshape, order='C')  
(consulte el Manual online de Numpy en: https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

a: es el array original  
newshape: es la cantidad de valores en cada eje que deseamos que tenga el resultado 



Supongamos que creamos un array con los 9 números enteros del 1 al 9.

In [53]:
numeros=np.arange(1,10,1)
numeros

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

y ahora queremos disponerlos en forma de matriz de 3 filas y 3 columnas, un una matriz es decir un array de 2 ejes:

In [100]:
np.reshape(numeros,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Por supuesto que no era necesario crear primero el array numeros, podríamos haber hecho:

In [34]:
np.reshape(np.arange(1,10,1),(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Ejercicio:  
Cree la siguiente matriz:
$$\begin{bmatrix} 1 & 1.5 & 2 & 2.5\\ 3 & 3.5 & 4 & 4.5\\ 5 & 5.5 & 6 & 6.5 \end{bmatrix}$$ 

In [36]:
#Escriba aquí su código
import numpy as np
A1=np.arange(1,7,0.5)
np.reshape(A1,(3,4))

array([[1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5]])

También es posible cambiar una matriz en otra, con los mismos números pero distinta cantidad de filas y columnas:

In [37]:
matriz_01=np.reshape(np.arange(1,13,1),(3,4))
matriz_01

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
matriz_02=np.reshape(matriz_01,(4,3))
matriz_02

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Convierta matriz_01 en una matriz con 6 filas y 2 columnas:

In [41]:
# Escriba aquí su código
M_3= np.reshape(matriz_01,(6,2))
M_3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Ahora conviértala en una matriz que tenga 2 filas y 6 columnas

In [42]:
# Escriba aquí su código
M_4= np.reshape(matriz_01,(2,6))
M_4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

**El uso de -1 en reshape**  

En algunas circunstancias el -1 puede funcionar como un comodín, observe el siguiente código:

In [43]:
np.reshape(matriz_01,(2,-1))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Observe el siguiente código:

In [45]:
np.reshape(matriz_01,(-1,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Explique aquí, qué papel jugó el -1 en los dos casos anteriores: 

El -1 termina de ordenar la matriz para que quede bien hecho el arreglo


### Flatten

Flatten sirve para transformar un array de varios ejes en uno de un solo eje, su sintaxis es como la siguiente:  

**matriz.flatten()**


In [129]:
matriz_01.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Cómo hubiera transformado a matriz_01 en un vector pero usando reshape?

In [50]:
# Escriba aquí su código
np.reshape(matriz_01,(1,-1)) #Aca hay duda con el -1


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

### Transpuesta de una matriz

Para transponer una matriz, simplemente:  
    
matriz.T    

Recordemos cómo era la matriz_01 y luego hallemos su transpuesta:

In [137]:
matriz_01

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
matriz_01.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## Arrays Booleanos

A veces será necesario crear arrays con valores True o False, esto también es posible en NumPy

In [143]:
np.array([[True,False],[False,True]])

array([[ True, False],
       [False,  True]])

También podríamos crear una matriz 3x3 con todos False

In [145]:
np.full((3, 3), False)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

Cree una matriz 2x4 con valores True

In [51]:
# Escriba aquí su código
np.full((2,4), True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Los arrays con valores booleanos suelen aparecer como resultados de ciertas operaciones, por ejemplo cuando comparamos valores:


Se acuerda cómo era el vector numeros?

In [54]:
numeros

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
numeros == 3

array([False, False,  True, False, False, False, False, False, False])

Observe que devolvió un array con True en las posiciones en las cuales se cumplió la condición y con  False en aquellas donde no se cumplió la condición.

En qué ubicaciones se encuentran los valores mayores a 4?

In [56]:
# Escriba aquí su código
numeros>4

array([False, False, False, False,  True,  True,  True,  True,  True])

y para los mayores o iguales a 4?

In [58]:
# Escriba aquí su código
numeros >= 4

array([False, False, False,  True,  True,  True,  True,  True,  True])

## Truco

Cuántos elementos mayores o iguales a 4 hay en el vector numeros?

In [158]:
sum(numeros>=4)

6

Ocurre que internamente maneja a los True como unos y a los False como 0, por eso funciona.

Cree una matriz de 10x4 con números aleatorios entre 1 y 100 inclusive generados con la semilla (seed=321). Llámela matriz 

In [60]:
# Escriba aqui su código
np.random.seed([321])
matriz = np.random.randint(1,101,(10,4))
matriz

array([[80, 34, 74, 62],
       [66,  5, 41, 53],
       [40, 23, 64, 77],
       [60, 18, 87, 39],
       [50, 72, 76, 85],
       [15, 67, 17, 12],
       [68, 66, 40, 46],
       [29, 77,  1, 97],
       [45, 79, 36, 35],
       [69, 39,  2, 31]])

Cuente cuántos de sus elementos son mayores o iguales que 20

In [64]:
# Escriba aqui su código
sum(matriz>=20)

array([9, 8, 7, 9])

In [176]:
# Escriba aqui su código

33